// Generated by translate-site-core.cjs. Links and route kinds are restored from the English source.
export const homeCopyOverrides = {
  "ar": {
    "title": "وثائق Notemd",
    "description": "سلاسل عمل معرفية تعتمد على الذكاء الاصطناعي لملاحظات Obsidian.",
    "eyebrow": "وثائق إضافة Obsidian",
    "heading": "Notemd",
    "lead": "أنشئ قاعدة معرفية دائمة من الملاحظات باستخدام روابط الويكي، وملاحظات المفاهيم، وملخصات البحث، والترجمة، والرسوم التوضيحية، بالإضافة إلى سلاسل عمل قابلة لإعادة الاستخدام بنقرة واحدة.",
    "primary": "اقرأ الوثائق",
    "secondary": "بدء سريع",
    "faq": "أسئلة شائعة",
    "factHeading": "حقائق المنتج المستندة إلى المصادر",
    "facts": [
      {
        "label": "نموذج سلسلة العمل",
        "value": "أتمتة في Obsidian تعتمد على الكتابة أولاً، وليست محض نص محادثة"
      },
      {
        "label": "قائمة المزودين",
        "value": "36 مزوداً من السحابة، والبوابات، والصين، والنماذج المحلية"
      },
      {
        "label": "حدود الخزنة",
        "value": "تُكتب النتائج مرة أخرى في ملفات Markdown المحلية"
      },
      {
        "label": "الإصدار الحالي",
        "value": "وثائق عامة للإصدار 1.9.7 وموارد الإصدار"
      }
    ],
    "retrievalHeading": "خريطة مصدر محرك الإجابات",
    "retrievalLead": "يعرض الموقع العام الآن نفس المسارات القياسية التي يصفها ملف llms.txt، وsitemap، وبيانات hreflang، وJSON-LD. استخدم هذه الصفحات كمصدر حقيقي لسلاسل عمل البحث بالذكاء الاصطناعي والاقتباس.",
    "languageBoundary": "حدود اللغة: تم التحقق من أن المستندات باللغتين الإنجليزية والصينية المبسطة قابلة للفهرسة؛ تظل جميع مسارات اللغات الأخرى متاحة للمراجعة وتم وضع علامة عليها بأنها مترجمة آليًا.",
    "retrievalLinks": [
      {
        "title": "خريطة استرجاع llms.txt",
        "body": "خريطة مسارات مدمجة لمحركات الإجابات، والوثائق القياسية، ومواضيع المزودين، ومجموعة المسارات متعددة اللغات الحالية.",
        "href": "/llms.txt",
        "kind": "static"
      },
      {
        "title": "إعدادات المزودين",
        "body": "الإعداد التشغيلي، وسلوك نقاط النهاية/المصادقة، واكتشاف النماذج، وحل المشكلات، وحدود حالات الاستخدام.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "سلسلة عمل المعرفة بالذكاء الاصطناعي",
        "body": "صفحة الركيزة القياسية لروابط الويكي، وملاحظات المفاهيم، والبحث، والترجمة، والرسوم التوضيحية، وسلاسل العمل.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ],
    "sections": [
      {
        "title": "ابدأ بأمان",
        "body": "قم بتثبيت الإضافة، وقم بتكوين مزود نموذج لغوي محلي أو سحابي، ثم شغّل أول سلسلة عمل لمعالجة الملاحظات الخاصة بك.",
        "href": "/docs/getting-started/quick-start"
      },
      {
        "title": "اختر المزودين",
        "body": "قارن بين خيارات النماذج المتوافقة مع OpenAI، وAnthropic، وGoogle، والموجهة للصين، والبوابات، والنماذج المحلية.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "أنشئ قاعدة معرفية",
        "body": "استخدم روابط الويكي المنظمة، وملاحظات المفاهيم، والبحث، والترجمة، وإنشاء الرسوم التوضيحية كنظام قابل للتكرار.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ]
  },
  "bn": {
    "title": "Notemd Documentation",
    "description": "Obsidian notes-এর জন্য AI-চালিত জ্ঞান ওয়ার্কফ্লো।",
    "eyebrow": "Obsidian plugin documentation",
    "heading": "Notemd",
    "lead": "wiki-links, concept notes, research summaries, translation, diagrams, এবং reusable one-click workflows ব্যবহার করে নোটগুলি থেকে স্থায়ী জ্ঞান তৈরি করুন।",
    "primary": "Read the docs",
    "secondary": "Quick start",
    "faq": "FAQ",
    "factHeading": "Source-backed product facts",
    "facts": [
      {
        "label": "Workflow model",
        "value": "Write-first Obsidian automation, not a chat transcript"
      },
      {
        "label": "Provider surface",
        "value": "36 cloud, gateway, China, এবং local LLM providers"
      },
      {
        "label": "Vault boundary",
        "value": "Outputs are written back into local Markdown files"
      },
      {
        "label": "Current release",
        "value": "Version 1.9.7 public docs and release assets"
      }
    ],
    "retrievalHeading": "Answer-engine source map",
    "retrievalLead": "পাবলিক সাইটটি এখন llms.txt, sitemap, hreflang metadata, এবং JSON-LD দ্বারা বর্ণিত একই canonical routes প্রদান করে। AI search ও citation workflows-এর জন্য এই পৃষ্ঠাগুলিকে সত্যের উৎস হিসেবে ব্যবহার করুন।",
    "languageBoundary": "ভাষা সীমানা: ইংরেজি এবং সরলীকৃত চীনা ভাষার ডকুমেন্টগুলো যাচাই করে ইনডেক্সযোগ্য হিসেবে চিহ্নিত করা হয়েছে; অন্যান্য সমস্ত লোকেল রুটগুলো পর্যালোচনার জন্য উপলব্ধ রয়েছে এবং সেগুলোকে মেশিন-অনুবাদিত হিসেবে চিহ্নিত করা হয়েছে।",
    "retrievalLinks": [
      {
        "title": "llms.txt retrieval map",
        "body": "answer engines, canonical docs, provider topics, এবং বর্তমান multilingual route set-এর জন্য Compact route map।",
        "href": "/llms.txt",
        "kind": "static"
      },
      {
        "title": "Provider configuration",
        "body": "Operational setup, endpoint/auth behavior, model discovery, troubleshooting, এবং use-case boundaries।",
        "href": "/docs/providers/overview"
      },
      {
        "title": "AI knowledge workflow",
        "body": "wiki-links, concept notes, research, translation, diagrams, এবং workflows-এর জন্য canonical pillar page।",
        "href": "/docs/pillar-ai-knowledge"
      }
    ],
    "sections": [
      {
        "title": "Start safely",
        "body": "Plugin-টি install করুন, একটি local বা cloud LLM provider configure করুন, এবং আপনার প্রথম note-processing workflow চালান।",
        "href": "/docs/getting-started/quick-start"
      },
      {
        "title": "Choose providers",
        "body": "OpenAI-compatible, Anthropic, Google, China-focused, gateway, এবং local model options-গুলির মধ্যে তুলনা করুন।",
        "href": "/docs/providers/overview"
      },
      {
        "title": "Build a knowledge base",
        "body": "structured wiki-linking, concept notes, research, translation, এবং diagram generation-কে একটি repeatable system হিসেবে ব্যবহার করুন।",
        "href": "/docs/pillar-ai-knowledge"
      }
    ]
  },
  "cs": {
    "title": "Dokumentace Notemd",
    "description": "Pracovní postupy pro zpracování znalostí pomocí AI pro poznámky v Obsidianu.",
    "eyebrow": "Dokumentace pluginu pro Obsidian",
    "heading": "Notemd",
    "lead": "Vytvářejte trvalé znalosti z poznámek pomocí odkazů na wiki, konceptových poznámek, shrnutí výzkumu, překladu, diagramů a opakovaně použitelných pracovních postupů jedním kliknutím.",
    "primary": "Přečíst si dokumentaci",
    "secondary": "Rychlý start",
    "faq": "Časté otázky",
    "factHeading": "Fakta o produktu podložená zdroji",
    "facts": [
      {
        "label": "Model pracovního postupu",
        "value": "Automatizace v Obsidianu typu Write-first, nikoli přepis konverzace"
      },
      {
        "label": "Možnosti poskytovatelů",
        "value": "36 cloudových, gatewayových, čínských a lokálních poskytovatelů LLM"
      },
      {
        "label": "Hranice vaultu",
        "value": "Výstupy jsou zpět zapisovány do lokálních souborů ve formátu Markdown"
      },
      {
        "label": "Aktuální verze",
        "value": "Veřejná dokumentace a soubory verze 1.9.7"
      }
    ],
    "retrievalHeading": "Mapa zdrojů pro engine odpovědí",
    "retrievalLead": "Veřejná stránka nyní poskytuje stejné kanonické cesty, které popisují soubory llms.txt, sitemap, metadata hreflang a JSON-LD. Tyto stránky používejte jako zdroj pravdy pro pracovní postupy vyhledávání pomocí AI a citací.",
    "languageBoundary": "Hranice jazyka: Dokumenty v angličtině a zjednodušené čínštině byly ověřeny jako indexovatelné; všechny ostatní cesty pro jednotlivé jazyky zůstávají k přezkoumání a jsou označeny jako strojově přeložené.",
    "retrievalLinks": [
      {
        "title": "Mapa vyhledávání llms.txt",
        "body": "Kompaktní mapa cest pro engine odpovědí, kanonické dokumentace, témata poskytovatelů a aktuální multijazyčnou sadu cest.",
        "href": "/llms.txt",
        "kind": "static"
      },
      {
        "title": "Konfigurace poskytovatelů",
        "body": "Provozní nastavení, chování koncovek/autentizace, vyhledávání modelů, řešení problémů a hranice použití.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "Pracovní postup AI pro znalosti",
        "body": "Kanonická hlavní stránka pro odkazy na wiki, konceptové poznámky, výzkum, překlad, diagramy a pracovní postupy.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ],
    "sections": [
      {
        "title": "Začněte bezpečně",
        "body": "Nainstalujte plugin, nakonfigurujte lokálního nebo cloudového poskytovatele LLM a spusťte svůj první pracovní postup pro zpracování poznámek.",
        "href": "/docs/getting-started/quick-start"
      },
      {
        "title": "Vyberte si poskytovatele",
        "body": "Porovnejte možnosti modelů kompatibilních s OpenAI, Anthropic, Google, zaměřené na Čínu, gatewayové a lokální modely.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "Vytvořte databázi znalostí",
        "body": "Využijte strukturované odkazy na wiki, konceptové poznámky, výzkum, překlad a generování diagramů jako opakovaně použitelný systém.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ]
  },
  "da": {
    "title": "Notemd-dokumentation",
    "description": "AI-styrte kunnskapsarbejdsmetoder for Obsidian-noter.",
    "eyebrow": "Obsidian-plugin-dokumentation",
    "heading": "Notemd",
    "lead": "Byg gennemgangelig kunnskab fra noter med wiki-linker, konceptnoter, forskningsopsummeringer, oversætning, diagrammer og brugbare en-klik arbejdsmetoder.",
    "primary": "Læs dokumentationen",
    "secondary": "Snabb start",
    "faq": "FAQ",
    "factHeading": "Produktfakta støttet af kilder",
    "facts": [
      {
        "label": "Arbejdsmetodemodell",
        "value": "Obsidian-automatisering baseret på skrivning først, ikke en chat-transkript"
      },
      {
        "label": "Tilbudsgivere",
        "value": "36 cloud-, gateway-, Kina- og lokale LLM-tilbudsgivere"
      },
      {
        "label": "Vault-grænser",
        "value": "Resultater skrives tilbake i lokale Markdown-filer"
      },
      {
        "label": "Aktuel udgave",
        "value": "Version 1.9.7 – offentlige dokumenter og udgivelsesfiler"
      }
    ],
    "retrievalHeading": "Kildekort for svarmaskiner",
    "retrievalLead": "Den offentlige side exponerer nu de samme kanoniske rutter som llms.txt, sitemap, hreflang-metadata og JSON-LD beskriver. Brug disse sider som kildet til sannhed for AI-søgning og citeringsarbejdsmetoder.",
    "languageBoundary": "Sproggrænse: Dokumenter på engelsk og simplificeret kinesisk er verifiserte som indeksbare; alle andre lokalspråksveje er fortsat tilgjengelige for granskning og er markeret som maskintolket.",
    "retrievalLinks": [
      {
        "title": "llms.txt-retrieval-kort",
        "body": "Kompakt rutterkort for svarmaskiner, kanoniske dokumenter, tilbudsgivertematerier og den aktuelle multilingvale rutterkatalog.",
        "href": "/llms.txt",
        "kind": "static"
      },
      {
        "title": "Konfiguration af tilbudsgivere",
        "body": "Operativ indstilling, endpoint/auth-behov, modelludvikling, fejlfinding og brugsområdegrænser.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "AI-kunnskapsarbejdsmetode",
        "body": "Den kanoniske hovedside for wiki-linker, konceptnoter, forskning, oversætning, diagrammer og arbejdsmetoder.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ],
    "sections": [
      {
        "title": "Start sikret",
        "body": "Installér pluginen, konfigurer en lokal eller cloud-baseret LLM-tilbudsgivere og køre din første notbehandlingsarbejdsmetode.",
        "href": "/docs/getting-started/quick-start"
      },
      {
        "title": "Vælg tilbudsgivere",
        "body": "Jegn op OpenAI-kompatible, Anthropic, Google, Kina-fokuserede, gateway- og lokale modellvalg.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "Byg en kunnskabsbase",
        "body": "Brug struktureret wiki-linking, konceptnoter, forskning, oversætning og diagramgenerering som et gennemførligt system.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ]
  },
  "de": {
    "title": "Notemd-Dokumentation",
    "description": "KI-gestützte Wissensworkflows für Obsidian-Notizen.",
    "eyebrow": "Dokumentation des Obsidian-Plugins",
    "heading": "Notemd",
    "lead": "Erstellen Sie dauerhaftes Wissen aus Notizen mithilfe von Wiki-Verknüpfungen, Konzeptnotizen, Forschungssammlungen, Übersetzungen, Diagrammen sowie wiederverwendbaren One‑Click‑Workflows.",
    "primary": "Dokumentation lesen",
    "secondary": "Schneller Einstieg",
    "faq": "FAQ",
    "factHeading": "Produktfakten mit Quellenbezug",
    "facts": [
      {
        "label": "Workflow‑Modell",
        "value": "Obsidian‑Automatisierung, die zuerst geschrieben wird, nicht ein Chat‑Transkript"
      },
      {
        "label": "Anbieterangebot",
        "value": "36 Cloud-, Gateway-, China‑ sowie lokale LLM‑Anbieter"
      },
      {
        "label": "Grenzen des Vaults",
        "value": "Die Ausgaben werden wieder in lokale Markdown‑Dateien geschrieben"
      },
      {
        "label": "Aktuelle Version",
        "value": "Version 1.9.7 – öffentliche Dokumentation und Release‑Ressourcen"
      }
    ],
    "retrievalHeading": "Quellkarte des Antwort‑Engines",
    "retrievalLead": "Die öffentliche Seite stellt nun dieselben kanonischen Routen bereit, wie sie in llms.txt, sitemap, hreflang‑Metadaten sowie JSON‑LD beschrieben werden. Nutzen Sie diese Seiten als Quelle der Wahrheit für KI‑Suche‑ und Zitierworkflows.",
    "languageBoundary": "Sprachgrenze: Englisch und Chinesisch (vereinfacht) sind als indexierbare Dokumentoberflächen bestätigt; alle anderen Sprachroute werden weiterhin zur Überprüfung bereitgestellt und als maschinell übersetzt gekennzeichnet.",
    "retrievalLinks": [
      {
        "title": "Retrieval‑Karte von llms.txt",
        "body": "Kompakte Routenkarte für Antwort‑Engines, kanonische Dokumentationen, Anbieterthemen sowie das aktuelle multilinguale Routensatz.",
        "href": "/llms.txt",
        "kind": "static"
      },
      {
        "title": "Konfiguration der Anbieter",
        "body": "Betriebsaufbau, Verhalten von Endpunkten/Authentifizierung, Modell‑Entdeckung, Fehlerbehebung sowie Grenzen der Anwendungsfälle.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "KI‑Wissensworkflow",
        "body": "Die kanonische Hauptseite für Wiki-Verknüpfungen, Konzeptnotizen, Forschung, Übersetzungen, Diagramme und Workflows.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ],
    "sections": [
      {
        "title": "Sicher starten",
        "body": "Installieren Sie das Plugin, konfigurieren Sie einen lokalen oder Cloud‑LLM‑Anbieter und führen Sie Ihren ersten Notiz‑Verarbeitungs‑Workflow aus.",
        "href": "/docs/getting-started/quick-start"
      },
      {
        "title": "Anbieter auswählen",
        "body": "Vergleichen Sie OpenAI‑kompatible, Anthropic-, Google-, China‑fokussierte, Gateway‑ sowie lokale Modelloptionen.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "Eine Wissensdatenbank erstellen",
        "body": "Verwenden Sie strukturierte Wiki-Verknüpfungen, Konzeptnotizen, Forschung, Übersetzungen und Diagrammgenerierung als wiederholbares System.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ]
  },
  "el": {
    "title": "Εγγράφηση Notemd",
    "description": "Διεργασίες εργασίας γνώσης με την τεχνολογία AI για σημειώσεις Obsidian.",
    "eyebrow": "Εγγράφηση πρόσθετου Obsidian",
    "heading": "Notemd",
    "lead": "Δημιουργήστε μόνιμη γνώση από σημειώσεις χρησιμοποιώντας συνδέσμους wiki, σημειώσεις έννοιας, σύνοψεις έρευνας, μετάφραση, διαγράμματα και επαναχρησιμοποιήσιμες διεργασίες με ένα κλικ.",
    "primary": "Διαβάστε την εγγράφηση",
    "secondary": "Γρήγορη αρχή",
    "faq": "FAQ",
    "factHeading": "Στοιχεία προϊόντος με βάση πηγές",
    "facts": [
      {
        "label": "Μοντέλο διεργασίας εργασίας",
        "value": "Αυτοματοποίηση Obsidian με πρώτη συγγραφή, όχι αντίγραφο συνομιλίας"
      },
      {
        "label": "Επιφάνεια παρόχων",
        "value": "36 παρόχοι cloud, gateway, Κίνα και τοπικοί LLM"
      },
      {
        "label": "Γρανίτες Vault",
        "value": "Τα αποτελέσματα γράφονται πίσω σε τοπικά αρχεία Markdown"
      },
      {
        "label": "Τρέχουσα έκδοση",
        "value": "Έκδοση 1.9.7 – δημόσια εγγράφηση και αντικείμενα έκδοσης"
      }
    ],
    "retrievalHeading": "Χάρτης πηγών μηχανής απαντήσεων",
    "retrievalLead": "Ο δημόσιος ιστότοπος παρουσιάζει τώρα τις ίδιες κανονικές διευθύνσεις που περιγράφονται στα llms.txt, sitemap, metadata hreflang και JSON-LD. Χρησιμοποιήστε αυτές τις σελίδες ως πηγή αλήθειας για διεργασίες αναζήτησης AI και αποσπασμάτων.",
    "languageBoundary": "Σύνορο γλώσσας: Τα έγγραφα στα αγγλικά και στα απλοποιημένα κινεζικά έχουν επαληθευτεί ως διαθέσιμα για αναζήτηση· όλες οι υπόλοιπες διαδρομές γλώσσας παραμένουν διαθέσιμες για ανασκόπηση και σηματοδοτούνται ως μηχανικά μεταφρασμένες.",
    "retrievalLinks": [
      {
        "title": "Χάρτης ανακτήσεων llms.txt",
        "body": "Συμπαγής χάρτης διευθύνσεων για μηχανές απαντήσεων, κανονικές εγγράφησεις, θέματα παρόχων και το τρέχον πολυγλωσσικό σύνολο διευθύνσεων.",
        "href": "/llms.txt",
        "kind": "static"
      },
      {
        "title": "Ρύθμιση παρόχων",
        "body": "Επιχειρησιακή ρύθμιση, συμπεριφορά endpoint/auth, ανακάλυψη μοντέλων, επίλυση προβλημάτων και όρια περιπτώσεων χρήσης.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "Διεργασία εργασίας γνώσης AI",
        "body": "Η κανονική σελίδα πυλώνα για συνδέσμους wiki, σημειώσεις έννοιας, έρευνα, μετάφραση, διαγράμματα και διεργασίες εργασίας.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ],
    "sections": [
      {
        "title": "Ξεκινήστε με ασφάλεια",
        "body": "Εγκαταστήστε το πρόσθετο, ρυθμίστε έναν τοπικό ή cloud παρόχο LLM και εκτελέστε την πρώτη διεργασία επεξεργασίας σημειώσεων σας.",
        "href": "/docs/getting-started/quick-start"
      },
      {
        "title": "Επιλέξτε παρόχους",
        "body": "Συγκρίνετε επιλογές που συμβαδίζουν με το OpenAI, Anthropic, Google, εστιάζουν στην Κίνα, gateway και τοπικά μοντέλα.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "Δημιουργήστε μία βάση γνώσης",
        "body": "Χρησιμοποιήστε δομημένα συνδέσμους wiki, σημειώσεις έννοιας, έρευνα, μετάφραση και δημιουργία διαγράμματων ως επαναλαμβάνιμο σύστημα.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ]
  },
  "es": {
    "title": "Documentación de Notemd",
    "description": "Flujos de trabajo de conocimiento impulsados por IA para notas de Obsidian.",
    "eyebrow": "Documentación del complemento de Obsidian",
    "heading": "Notemd",
    "lead": "Cree un conocimiento persistente a partir de notas mediante enlaces wiki, notas conceptuales, resúmenes de investigación, traducción, diagramas y flujos de trabajo reutilizables con un solo clic.",
    "primary": "Leer la documentación",
    "secondary": "Inicio rápido",
    "faq": "Preguntas frecuentes",
    "factHeading": "Hechos del producto respaldados por fuentes",
    "facts": [
      {
        "label": "Modelo de flujo de trabajo",
        "value": "Automatización en Obsidian basada en la escritura primero, no en transcripciones de chat"
      },
      {
        "label": "Opciones de proveedores",
        "value": "36 proveedores de LLM en la nube, a través de pasarelas, en China y locales"
      },
      {
        "label": "Límite del vault",
        "value": "Los resultados se escriben nuevamente en archivos Markdown locales"
      },
      {
        "label": "Versión actual",
        "value": "Documentación pública y recursos de la versión 1.9.7"
      }
    ],
    "retrievalHeading": "Mapa de fuentes del motor de respuestas",
    "retrievalLead": "El sitio público ahora expone las mismas rutas canónicas que describen llms.txt, sitemap, metadatos hreflang y JSON-LD. Utilice estas páginas como fuente de verdad para flujos de trabajo de búsqueda e inserción de citas por IA.",
    "languageBoundary": "Límite de idioma: se ha verificado que los documentos indexables están en inglés y chino simplificado; todas las demás rutas de idioma siguen estando disponibles para revisión y están marcadas como traducidas por máquina.",
    "retrievalLinks": [
      {
        "title": "Mapa de recuperación de llms.txt",
        "body": "Mapa de rutas compacto para motores de respuestas, documentos canónicos, temas de proveedores y el conjunto actual de rutas multilingües.",
        "href": "/llms.txt",
        "kind": "static"
      },
      {
        "title": "Configuración de proveedores",
        "body": "Configuración operativa, comportamiento de endpoints/auth, descubrimiento de modelos, solución de problemas y límites de casos de uso.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "Flujo de trabajo de conocimiento por IA",
        "body": "La página pilar canónica para enlaces wiki, notas conceptuales, investigación, traducción, diagramas y flujos de trabajo.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ],
    "sections": [
      {
        "title": "Comience con seguridad",
        "body": "Instale el complemento, configure un proveedor de LLM local o en la nube y ejecute su primer flujo de trabajo de procesamiento de notas.",
        "href": "/docs/getting-started/quick-start"
      },
      {
        "title": "Elija proveedores",
        "body": "Compare opciones compatibles con OpenAI, Anthropic, Google, enfocadas en China, a través de pasarelas y modelos locales.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "Cree una base de conocimiento",
        "body": "Utilice enlaces wiki estructurados, notas conceptuales, investigación, traducción y generación de diagramas como un sistema reutilizable.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ]
  },
  "fa": {
    "title": "مستندات Notemd",
    "description": "فرآیندهای کاری مبتنی بر هوش مصنوعی برای یادداشت‌های Obsidian.",
    "eyebrow": "مستندات پلاگین Obsidian",
    "heading": "Notemd",
    "lead": "با استفاده از لینک‌های ویکی، یادداشت‌های مفهومی، خلاصه‌های تحقیقاتی، ترجمه، نمودارها و فرآیندهای یک‌کلیک قابل استفاده مجدد، دانش پایداری از یادداشت‌ها ایجاد کنید.",
    "primary": "مستندات را بخوانید",
    "secondary": "شروع سریع",
    "faq": "سؤالات متداول",
    "factHeading": "حقایق محصول مبتنی بر منابع",
    "facts": [
      {
        "label": "مدل فرآیند کاری",
        "value": "خودکارسازی Obsidian با نوشتن اولیه، نه رونوشت گفت‌وگو"
      },
      {
        "label": "منابع ارائه‌دهنده",
        "value": "۳۶ ارائه‌دهنده LLM در ابر، گیت‌وی، چین و سطح محلی"
      },
      {
        "label": "مرزهای Vault",
        "value": "خروجی‌ها دوباره در فایل‌های Markdown محلی ذخیره می‌شوند"
      },
      {
        "label": "نسخه فعلی",
        "value": "مستندات عمومی و منابع نسخه ۱.۹.۶"
      }
    ],
    "retrievalHeading": "نقشه منبع موتور پاسخ‌دهی",
    "retrievalLead": "سایت عمومی اکنون همان مسیرهای استانداردی را ارائه می‌دهد که در فایل‌های llms.txt، sitemap، فراداده‌های hreflang و JSON-LD توصیف شده‌اند. از این صفحات به عنوان منبع صحیح برای فرآیندهای جستجوی هوش مصنوعی و استناد استفاده کنید.",
    "languageBoundary": "مرز زبانی: مستندات قابل فهرست‌سازی برای زبان‌های انگلیسی و چینی ساده تأیید شده‌اند؛ تمام مسیرهای زبانی دیگر همچنان برای بررسی در دسترس هستند و به عنوان متن‌های ترجمه‌شده توسط ماشین علامت‌گذاری شده‌اند.",
    "retrievalLinks": [
      {
        "title": "نقشه بازیابی llms.txt",
        "body": "نقشه مختصری برای موتورهای پاسخ‌دهی، مستندات استاندارد، موضوعات ارائه‌دهنده و مجموعه فعلی مسیرهای چندزبانه.",
        "href": "/llms.txt",
        "kind": "static"
      },
      {
        "title": "پیکربندی ارائه‌دهنده",
        "body": "بررسی عملیاتی، رفتار پایانه/احراز هویت، کشف مدل‌ها، رفع اشکال و مرزهای موارد استفاده.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "فرآیند کاری دانش هوش مصنوعی",
        "body": "صفحه اصلی استاندارد برای لینک‌های ویکی، یادداشت‌های مفهومی، تحقیقات، ترجمه، نمودارها و فرآیندهای کاری.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ],
    "sections": [
      {
        "title": "به‌طور ایمن شروع کنید",
        "body": "پلاگین را نصب کنید، یک ارائه‌دهنده LLM محلی یا ابری پیکربندی کنید و اولین فرآیند پردازش یادداشت خود را اجرا کنید.",
        "href": "/docs/getting-started/quick-start"
      },
      {
        "title": "ارائه‌دهنده‌ها را انتخاب کنید",
        "body": "گزینه‌های مدل‌های سازگار با OpenAI، Anthropic، Google، متمرکز بر چین، گیت‌وی و مدل‌های محلی را مقایسه کنید.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "یک پایگاه دانش ایجاد کنید",
        "body": "از لینک‌های ساختاریافته ویکی، یادداشت‌های مفهومی، تحقیقات، ترجمه و تولید نمودارها به عنوان یک سیستم قابل تکرار استفاده کنید.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ]
  },
  "fi": {
    "title": "Notemd - dokumentaatio",
    "description": "AI-voimistettu tietojen hallintatyöprosessit Obsidian -notioille.",
    "eyebrow": "Obsidian -pluginin dokumentaatio",
    "heading": "Notemd",
    "lead": "Luo kestävät tietotekot notioista käyttäen wiki-liitteitä, konsepttikirjeitä, tutkimusyhteenvetoja, kääntöä, diagrammeja sekä uudelleen käytettäviä yhden painutuksen kanssa toimivia työprosesseja.",
    "primary": "Lue dokumentaatio",
    "secondary": "Nopea alustus",
    "faq": "Kysymyksiä ja vastauksia",
    "factHeading": "Tuotteen faktat lähteistöjen perusteella",
    "facts": [
      {
        "label": "Työprosessin malli",
        "value": "Alkaa kirjoittamisesta – Obsidian -automatisointi, ei chat -kirjoitus"
      },
      {
        "label": "Tarjoajien valikoima",
        "value": "36 pilvituotetta, gateway -palvelua, Hiinan tuotetta sekä lokalisoiduja LLM -tarjoajia"
      },
      {
        "label": "Vault -raja",
        "value": "Tulokset kirjoitetaan takaisin lokalisoihin Markdown -failiin"
      },
      {
        "label": "Päivitetty versio",
        "value": "Versio 1.9.7 – yleisillä dokumenteilla ja versiojen resurssilla"
      }
    ],
    "retrievalHeading": "Vastausmekanismien lähteekartta",
    "retrievalLead": "Yleisillä sivuillemilla on nyt samat kanoniset routit kuin llms.txt-, sitemap-, hreflang-meta-työkalut ja JSON-LD -tiedostot. Käytä näitä sivuja AI -hakukoneiden ja viitauksityöprosessien todellisuuslähteeksi.",
    "languageBoundary": "Kielipuoli: englanti ja yksinkertaisen kiinan kielillä olevat dokummentit ovat vahvistettuina indeksoituiksi; kaikki muut kielipuolien tiedot ovat edelleen käytettävissä arvioinnon tarkoituksessa ja merkittyjä masintulkituiksi.",
    "retrievalLinks": [
      {
        "title": "llms.txt -hakukoneen kartta",
        "body": "Kompakti kartta vastausmekanismille, kanonillisiin dokumenteihin, tarjoajien teemoihin sekä nykyiseen monikieliseen routinasetukselle.",
        "href": "/llms.txt",
        "kind": "static"
      },
      {
        "title": "Tarjoajien konfigurointi",
        "body": "Toiminnallinen asentaminen, päätuspisteiden/turvallisuustoiminnot, mallien löytö, ongelman ratkaisu sekä käyttötason rajat.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "AI-tietojen hallintatyöprosessi",
        "body": "Kanoninen pylvissivu wiki-liitteille, konsepttikirjeille, tutkimukseen, kääntöön, diagrammeihin sekä työprosesseihin.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ],
    "sections": [
      {
        "title": "Alusta turvallisesti",
        "body": "Asenna plugini, konfiguroi lokalisoinen tai pilvituotettu LLM -tarjoaja ja käynnista oma ensimmäinen notion hallintatyöprosessi.",
        "href": "/docs/getting-started/quick-start"
      },
      {
        "title": "Valitse tarjoajat",
        "body": "Verglellä OpenAI -sovelluvia, Anthropic-, Google-, Hiinan keskittyviä, gateway -palveluja sekä lokalisoiduja mallivalintoja.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "Luo tietotekosi",
        "body": "Käytä strukturoituja wiki-liitteitä, konsepttikirjeitä, tutkimusta, kääntöä sekä diagrammin luomista kerran toistettavana sistemana.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ]
  },
  "fr": {
    "title": "Documentation de Notemd",
    "description": "Flux de travail de connaissances pilotés par l'IA pour les notes Obsidian.",
    "eyebrow": "Documentation du plugin Obsidian",
    "heading": "Notemd",
    "lead": "Créez des connaissances persistantes à partir de vos notes grâce à des liens wiki, des notes conceptuelles, des résumés de recherche, des traductions, des diagrammes et des flux de travail réutilisables en un clic.",
    "primary": "Lire la documentation",
    "secondary": "Début rapide",
    "faq": "FAQ",
    "factHeading": "Faits sur le produit basés sur des sources fiables",
    "facts": [
      {
        "label": "Modèle de flux de travail",
        "value": "Automatisation Obsidian basée sur l’écriture en premier, et non une transcription de conversation"
      },
      {
        "label": "Éventail des fournisseurs",
        "value": "36 fournisseurs LLM cloud, via passerelle, chinois et locaux"
      },
      {
        "label": "Limites du coffre-fort",
        "value": "Les résultats sont réécrits dans des fichiers Markdown locaux"
      },
      {
        "label": "Version actuelle",
        "value": "Documentation publique et ressources de version 1.9.7"
      }
    ],
    "retrievalHeading": "Carte des sources du moteur de réponses",
    "retrievalLead": "Le site public expose désormais les mêmes routes canoniques que celles décrites dans llms.txt, sitemap, les métadonnées hreflang et JSON-LD. Utilisez ces pages comme source unique pour les flux de travail de recherche et de citation par l’IA.",
    "languageBoundary": "Limite de langue : les documents indexables en anglais et en chinois simplifié ont été vérifiés ; toutes les autres routes linguistiques restent disponibles pour révision et sont marquées comme étant traduites par machine.",
    "retrievalLinks": [
      {
        "title": "Carte de récupération llms.txt",
        "body": "Carte de routes compacte pour les moteurs de réponses, la documentation canonique, les sujets de fournisseurs et l’ensemble actuel des routes multilingues.",
        "href": "/llms.txt",
        "kind": "static"
      },
      {
        "title": "Configuration des fournisseurs",
        "body": "Mise en place opérationnelle, comportement des points d’accès/authentification, découverte de modèles, dépannage et limites des cas d’usage.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "Flux de travail de connaissances par l’IA",
        "body": "Page pilier canonique pour les liens wiki, les notes conceptuelles, la recherche, les traductions, les diagrammes et les flux de travail.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ],
    "sections": [
      {
        "title": "Commencer en toute sécurité",
        "body": "Installez le plugin, configurez un fournisseur LLM local ou cloud, puis exécutez votre premier flux de travail de traitement de notes.",
        "href": "/docs/getting-started/quick-start"
      },
      {
        "title": "Choisir des fournisseurs",
        "body": "Comparez les options compatibles OpenAI, Anthropic, Google, axées sur la Chine, via passerelle et les modèles locaux.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "Créer une base de connaissances",
        "body": "Utilisez des liens wiki structurés, des notes conceptuelles, de la recherche, des traductions et la génération de diagrammes comme système reproductible.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ]
  },
  "he": {
    "title": "מדריך Notemd",
    "description": "תהליכי עבודה של ידע המונעים על ידי AI עבור רשימות Obsidian.",
    "eyebrow": "מדריך תוסף Obsidian",
    "heading": "Notemd",
    "lead": "יצרו בסיס ידע קבוע מרשימות באמצעות לינקים של wiki, רשימות רעיונות, סיכומי מחקר, תרגום, דיאגרמות ותהליכי עבודה שניתן לשחזר בלחיצה אחת.",
    "primary": "קראו את המדריך",
    "secondary": "התחלה מהירה",
    "faq": "שאלות נפוצות",
    "factHeading": "עובדות על המוצר המבוססות על מקורות",
    "facts": [
      {
        "label": "מודל תהליך העבודה",
        "value": "אוטומציה של Obsidian שמתחילה בכתיבה, ולא תמליל של שיחה"
      },
      {
        "label": "מגוון הספקים",
        "value": "36 ספקי LLM בענן, גייטווי, בסין ולוקליים"
      },
      {
        "label": "גבולות ה‑Vault",
        "value": "התוצאות נכתבות בחזרה לקבצי Markdown המקומיים"
      },
      {
        "label": "הגרסה הנוכחית",
        "value": "מדריך ציבורי ונכסי גרסה 1.9.7"
      }
    ],
    "retrievalHeading": "מפת מקורות של מנועי תשובות",
    "retrievalLead": "האתר הציבורי חושף כעת את אותן דרכים קנוניות שמתוארות ב‑llms.txt, sitemap, מטא‑דאטה hreflang ו‑JSON‑LD. השתמשו בדפים אלה כמקור האמת לתהליכי חיפוש AI וציטוט.",
    "languageBoundary": "גבול שפה: מסמכים באנגלית ובסינית פשוטה אושרו כמסמכים שניתן לאינדקס; כל המסלולים של שפות אחרות עדיין זמינים לבדיקה ומסומנים כמתורגמים על ידי מכונה.",
    "retrievalLinks": [
      {
        "title": "מפת החיפוש llms.txt",
        "body": "מפת דרכים קומפקטית למנועי תשובות, מדריך קנוני, נושאי ספקים וקבוצת הדרכים רב‑השפתית הנוכחית.",
        "href": "/llms.txt",
        "kind": "static"
      },
      {
        "title": "הגדרת ספקים",
        "body": "הגדרה תפעולית, התנהגות endpoint/auth, גילוי מודלים, פתרון בעיות וגבולות של מקרי שימוש.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "תהליך עבודה של ידע AI",
        "body": "דף העמוד הקנוני ללינקים של wiki, רשימות רעיונות, מחקר, תרגום, דיאגרמות ותהליכי עבודה.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ],
    "sections": [
      {
        "title": "התחלה בבטחה",
        "body": "התקינו את התוסף, הגדירו ספק LLM מקומי או בענן, והריצו את תהליך עיבוד הרשימות הראשון שלכם.",
        "href": "/docs/getting-started/quick-start"
      },
      {
        "title": "בחירת ספקים",
        "body": "השוו אפשרויות של מודלים תואמי OpenAI, Anthropic, Google, מודלים המתמקדים בסין, גייטווי ומודלים לוקליים.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "יצירת בסיס ידע",
        "body": "השתמשו בלינקים מבוססי wiki, רשימות רעיונות, מחקר, תרגום ויצירת דיאגרמות כמערכת חוזרת על עצמה.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ]
  },
  "hi": {
    "title": "Notemd दस्तावेज़ीकरण",
    "description": "Obsidian नोट्स के लिए AI-संचालित ज्ञान कार्यप्रवाह।",
    "eyebrow": "Obsidian प्लगइन दस्तावेज़ीकरण",
    "heading": "Notemd",
    "lead": "विकि-लिंक, कॉन्सेप्ट नोट्स, अनुसंधान सारांश, अनुवाद, आरेख, एवं पुनः उपयोग योग्य वन-क्लिक कार्यप्रवाहों के साथ नोट्स से स्थायी ज्ञान बनाएँ।",
    "primary": "दस्तावेज़ पढ़ें",
    "secondary": "त्वरित शुरुआत",
    "faq": "FAQ",
    "factHeading": "स्रोत-समर्थित उत्पाद तथ्य",
    "facts": [
      {
        "label": "कार्यप्रवाह मॉडल",
        "value": "‘Write-first’ Obsidian स्वचालन, चैट ट्रांसक्रिप्ट नहीं"
      },
      {
        "label": "प्रदाता विकल्प",
        "value": "36 क्लाउड, गेटवे, चीन, एवं स्थानीय LLM प्रदाता"
      },
      {
        "label": "वॉल्ट सीमा",
        "value": "आउटपुट स्थानीय Markdown फ़ाइलों में ही लिखे जाते हैं"
      },
      {
        "label": "वर्तमान रिलीज़",
        "value": "संस्करण 1.9.7 के सार्वजनिक दस्तावेज़ एवं रिलीज़ संसाधन"
      }
    ],
    "retrievalHeading": "उत्तर-इंजन स्रोत मानचित्र",
    "retrievalLead": "सार्वजनिक साइट अब llms.txt, sitemap, hreflang मेटाडेटा, एवं JSON-LD द्वारा वर्णित उन्हीं मानक मार्गों को प्रदर्शित करती है। AI खोज एवं संदर्भ कार्यप्रवाहों के लिए इन पृष्ठों को सत्य का स्रोत मानें।",
    "languageBoundary": "भाषा सीमा: अंग्रेज़ी एवं सरलीकृत चीनी भाषा वाले दस्तावेज़ों को इंडेक्स किया जा सकता है; अन्य सभी भाषा मार्गों की समीक्षा के लिए उपलब्ध हैं एवं उन्हें मशीन-अनुवादित के रूप में चिह्नित किया गया है।",
    "retrievalLinks": [
      {
        "title": "llms.txt रिट्रीवल मानचित्र",
        "body": "उत्तर इंजनों, मानक दस्तावेज़ों, प्रदाता विषयों, एवं वर्तमान बहुभाषी मार्ग समूह के लिए संक्षिप्त मार्ग मानचित्र।",
        "href": "/llms.txt",
        "kind": "static"
      },
      {
        "title": "प्रदाता कॉन्फ़िगरेशन",
        "body": "संचालन सेटअप, एंडपॉइंट/प्रमाणीकरण व्यवहार, मॉडल खोज, समस्या निवारण, एवं उपयोग-मामला सीमाएँ।",
        "href": "/docs/providers/overview"
      },
      {
        "title": "AI ज्ञान कार्यप्रवाह",
        "body": "विकि-लिंक, कॉन्सेप्ट नोट्स, अनुसंधान, अनुवाद, आरेख, एवं कार्यप्रवाहों के लिए मानक पिलर पृष्ठ।",
        "href": "/docs/pillar-ai-knowledge"
      }
    ],
    "sections": [
      {
        "title": "सुरक्षित रूप से शुरू करें",
        "body": "प्लगइन इंस्टॉल करें, स्थानीय या क्लाउड LLM प्रदाता कॉन्फ़िगर करें, एवं अपना पहला नोट-प्रसंस्करण कार्यप्रवाह चलाएँ।",
        "href": "/docs/getting-started/quick-start"
      },
      {
        "title": "प्रदाता चुनें",
        "body": "OpenAI-संगत, Anthropic, Google, चीन-केंद्रित, गेटवे, एवं स्थानीय मॉडल विकल्पों की तुलना करें।",
        "href": "/docs/providers/overview"
      },
      {
        "title": "एक ज्ञान आधार बनाएँ",
        "body": "संरचित विकि-लिंकिंग, कॉन्सेप्ट नोट्स, अनुसंधान, अनुवाद, एवं आरेख निर्माण का उपयोग एक दोहराया जा सकने वाला सिस्टम के रूप में करें।",
        "href": "/docs/pillar-ai-knowledge"
      }
    ]
  },
  "hu": {
    "title": "Notemd dokumentáció",
    "description": "AI-támogatott tudományos munkafolyamatok Obsidian jegyeihez.",
    "eyebrow": "Obsidian plug-in dokumentáció",
    "heading": "Notemd",
    "lead": "Wiki-hivatkozások, konceptjegyek, kutatási összefoglalók, fordítások, diagramok és újrahasználható egy-kattintási munkafolyamatok segítségével jellegzetes tudományot készítsenek ki a jegyeikből.",
    "primary": "Lépjen be a dokumentációba",
    "secondary": "Rácsolás",
    "faq": "SSZK",
    "factHeading": "Forrásokkal alábíró termékinformációk",
    "facts": [
      {
        "label": "Munkafolyammodell",
        "value": "First-write Obsidian automatizálása, nem chat transzkripció"
      },
      {
        "label": "Társítók listája",
        "value": "36 felhő-, gateway-, Kína- és helyi LLM társító"
      },
      {
        "label": "A tárgyárma határai",
        "value": "A kiindulók visszakészülnek helyi Markdown fájlokba"
      },
      {
        "label": "Jelenlegi verzió",
        "value": "Verzió 1.9.7 – közösségi dokumentáció és verziós fájlok"
      }
    ],
    "retrievalHeading": "Answer-engine forráskárta",
    "retrievalLead": "A közösségi oldal most megjeleníti azokat a kanonikus útvonalakat, amelyeket llms.txt, sitemap, hreflang metadata és JSON-LD leír. Használja ezeket a oldalakat az AI keresési és citációs munkafolyamatoknak igazságforrásként.",
    "languageBoundary": "Nyelvi határvonal: az angol és a simplifikált kínai nyelvű dokumentációk ellenőrzve bejelöltek, hogy indexelhetőek legyenek; az összes más nyelvi út továbbra is megtekintésre k Disponibilizálva, és őket gépüberszólítottnak jelölték.",
    "retrievalLinks": [
      {
        "title": "llms.txt keresési kárta",
        "body": "Kompakt útvonalkárta answer engine-eknek, kanonikus dokumentációknak, társító témáknak és a jelenlegi többnyelvű útvonalainak csomagához.",
        "href": "/llms.txt",
        "kind": "static"
      },
      {
        "title": "Társítók konfigurálása",
        "body": "Működési beállítások, endpoint/auth viselkedés, modellkeresés, hibakeresés és használati esetek határai.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "AI tudományos munkafolyam",
        "body": "Wiki-hivatkozások, konceptjegyek, kutatás, fordítások, diagramok és munkafolyamatokhoz szóló kanonikus főoldal.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ],
    "sections": [
      {
        "title": "Biztonságosan kezdje el",
        "body": "Írja le a plug-in-t, konfigurálja egy helyi vagy felhőbeli LLM társítót, és futtasson el az első jegyekezelési munkafolyamát.",
        "href": "/docs/getting-started/quick-start"
      },
      {
        "title": "Válassza a társítókat",
        "body": "Összevetje OpenAI-kompatibilis, Anthropic, Google, Kína-ra fókuszált, gateway- és helyi modell opcióit.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "Készítsen ki egy tudományos bázist",
        "body": "Használja a struktúrált wiki-hivatkozásokat, konceptjegyeket, kutatást, fordítást és diagramkészítést egy újrahasználható rendszerként.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ]
  },
  "id": {
    "title": "Dokumentasi Notemd",
    "description": "Alur kerja pengetahuan berbasis AI untuk catatan Obsidian.",
    "eyebrow": "Dokumentasi plugin Obsidian",
    "heading": "Notemd",
    "lead": "Buat basis pengetahuan yang persisten dari catatan menggunakan tautan wiki, catatan konsep, ringkasan penelitian, terjemahan, diagram, serta alur kerja satu klik yang dapat digunakan kembali.",
    "primary": "Baca dokumen",
    "secondary": "Mulai dengan cepat",
    "faq": "FAQ",
    "factHeading": "Fakta produk yang didukung sumber",
    "facts": [
      {
        "label": "Model alur kerja",
        "value": "Otomatisasi Obsidian berbasis penulisan terlebih dahulu, bukan transkrip percakapan"
      },
      {
        "label": "Pilihan penyedia layanan",
        "value": "36 penyedia LLM berbasis cloud, gateway, China, dan lokal"
      },
      {
        "label": "Batas vault",
        "value": "Hasilnya ditulis kembali ke file Markdown lokal"
      },
      {
        "label": "Rilis terkini",
        "value": "Dokumen publik versi 1.9.7 beserta aset rilis"
      }
    ],
    "retrievalHeading": "Peta sumber mesin jawaban",
    "retrievalLead": "Situs publik kini menampilkan rute kanonik yang sama seperti yang dijelaskan oleh llms.txt, sitemap, metadata hreflang, dan JSON-LD. Gunakan halaman-halaman ini sebagai sumber kebenaran untuk alur kerja pencarian AI dan penulisan kutipan.",
    "languageBoundary": "Batas bahasa: Dokumen yang dapat diindeks dalam bahasa Inggris dan Tionghoa Sederhana telah diverifikasi; semua rute bahasa lainnya masih tersedia untuk ditinjau dan ditandai sebagai terjemahan mesin.",
    "retrievalLinks": [
      {
        "title": "Peta pencarian llms.txt",
        "body": "Peta rute yang kompak untuk mesin jawaban, dokumen kanonik, topik penyedia layanan, serta set rute multibahasa terkini.",
        "href": "/llms.txt",
        "kind": "static"
      },
      {
        "title": "Konfigurasi penyedia layanan",
        "body": "Pengaturan operasional, perilaku endpoint/auth, penemuan model, pemecahan masalah, serta batasan kasus penggunaan.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "Alur kerja pengetahuan AI",
        "body": "Halaman utama kanonik untuk tautan wiki, catatan konsep, penelitian, terjemahan, diagram, dan alur kerja.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ],
    "sections": [
      {
        "title": "Mulai dengan aman",
        "body": "Instal pluginnya, konfigurasikan penyedia LLM lokal atau berbasis cloud, lalu jalankan alur kerja pemrosesan catatan pertama Anda.",
        "href": "/docs/getting-started/quick-start"
      },
      {
        "title": "Pilih penyedia layanan",
        "body": "Bandingkan opsi model yang kompatibel dengan OpenAI, Anthropic, Google, yang fokus pada China, gateway, serta model lokal.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "Buat basis pengetahuan",
        "body": "Gunakan tautan wiki yang terstruktur, catatan konsep, penelitian, terjemahan, dan pembuatan diagram sebagai sistem yang dapat diulang.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ]
  },
  "it": {
    "title": "Documentazione di Notemd",
    "description": "Flussi di lavoro basati sull’AI per le note di Obsidian.",
    "eyebrow": "Documentazione del plugin per Obsidian",
    "heading": "Notemd",
    "lead": "Crea una conoscenza persistente a partire dalle note, utilizzando link wiki, note concettuali, riassunti di ricerca, traduzioni, diagrammi e flussi di lavoro riutilizzabili con un solo clic.",
    "primary": "Leggi la documentazione",
    "secondary": "Avvio rapido",
    "faq": "FAQ",
    "factHeading": "Fatti sul prodotto supportati dalle fonti",
    "facts": [
      {
        "label": "Modello di flusso di lavoro",
        "value": "Automazione in Obsidian basata sulla scrittura, non una trascrizione di chat"
      },
      {
        "label": "Elenco dei fornitori",
        "value": "36 fornitori LLM cloud, gateway, cinesi e locali"
      },
      {
        "label": "Confini del vault",
        "value": "Gli output vengono scritti nuovamente in file Markdown locali"
      },
      {
        "label": "Versione attuale",
        "value": "Documentazione pubblica e asset di rilascio della versione 1.9.7"
      }
    ],
    "retrievalHeading": "Mappa delle fonti del motore di risposta",
    "retrievalLead": "Il sito pubblico esporrà ora le stesse rotte canoniche descritte da llms.txt, sitemap, metadati hreflang e JSON-LD. Utilizza queste pagine come fonte di verità per i flussi di lavoro di ricerca e citazione basati sull’AI.",
    "languageBoundary": "Confini linguistici: gli indici verificabili in inglese e cinese semplificato sono stati confermati; tutte le altre rotte di locale rimangono disponibili per la revisione ed sono contrassegnate come tradotte automaticamente.",
    "retrievalLinks": [
      {
        "title": "Mappa di recupero di llms.txt",
        "body": "Mappa di rotte compatta per i motori di risposta, la documentazione canonica, gli argomenti sui fornitori e l’attuale insieme di rotte multilingue.",
        "href": "/llms.txt",
        "kind": "static"
      },
      {
        "title": "Configurazione dei fornitori",
        "body": "Impostazioni operative, comportamento degli endpoint/auth, scoperta dei modelli, risoluzione dei problemi e confini degli scenari d’uso.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "Flusso di lavoro di conoscenza AI",
        "body": "La pagina pilastro canonica per link wiki, note concettuali, ricerca, traduzioni, diagrammi e flussi di lavoro.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ],
    "sections": [
      {
        "title": "Inizia in sicurezza",
        "body": "Installa il plugin, configura un fornitore LLM locale o cloud e avvia il tuo primo flusso di lavoro di elaborazione delle note.",
        "href": "/docs/getting-started/quick-start"
      },
      {
        "title": "Scegli i fornitori",
        "body": "Confronta le opzioni compatibili con OpenAI, Anthropic, Google, focalizzate sulla Cina, gateway e modelli locali.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "Crea una base di conoscenza",
        "body": "Utilizza link wiki strutturati, note concettuali, ricerca, traduzioni e generazione di diagrammi come sistema ripetibile.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ]
  },
  "ja": {
    "title": "Notemd ドキュメント",
    "description": "Obsidian のノート向けに、AI 機構を活用した知識ワークフローを提供します。",
    "eyebrow": "Obsidian プラグインのドキュメント",
    "heading": "Notemd",
    "lead": "ウィキリンク、コンセプトノート、調査要約、翻訳、図表、そして再利用可能なワンクリックワークフローを用いて、ノートから永続的な知識ベースを構築できます。",
    "primary": "ドキュメントを読む",
    "secondary": "クイックスタート",
    "faq": "FAQ",
    "factHeading": "信頼できる製品情報",
    "facts": [
      {
        "label": "ワークフローモデル",
        "value": "チャットの転記ではなく、まず執筆する型の Obsidian 自動化です"
      },
      {
        "label": "プロバイダの種類",
        "value": "36 種類のクラウド、ゲートウェイ、中国向け、およびローカル LLM プロバイダが利用可能です"
      },
      {
        "label": "Vault の仕組み",
        "value": "出力結果はローカルの Markdown ファイルに書き戻されます"
      },
      {
        "label": "現在のリリースバージョン",
        "value": "バージョン 1.9.7 の公式ドキュメントおよびリリースアセットが公開されています"
      }
    ],
    "retrievalHeading": "回答エンジンのソースマップ",
    "retrievalLead": "現在の公開サイトでは、llms.txt、sitemap、hreflang メタデータ、JSON-LD で記述されているのと同じ正規ルートが提供されています。これらのページを AI 検索や引用ワークフローの信頼できる情報源としてご利用ください。",
    "languageBoundary": "言語境界：英語および簡体中国語のドキュメントはインデックス可能な対象として確認されています。その他のすべてのロケールのページもレビュー用として利用可能であり、機械翻訳済みとしてマークされています。",
    "retrievalLinks": [
      {
        "title": "llms.txt の検索マップ",
        "body": "回答エンジン、正規ドキュメント、プロバイダのトピック、そして現在の多言語ルートセットをまとめたコンパクトなマップです。",
        "href": "/llms.txt",
        "kind": "static"
      },
      {
        "title": "プロバイダの設定方法",
        "body": "運用上のセットアップ、エンドポイント/認証の動作、モデルの検出、トラブルシューティング、および利用ケースの範囲について説明しています。",
        "href": "/docs/providers/overview"
      },
      {
        "title": "AI 知識ワークフロー",
        "body": "ウィキリンク、コンセプトノート、調査、翻訳、図表、ワークフローに関する公式のポータルページです。",
        "href": "/docs/pillar-ai-knowledge"
      }
    ],
    "sections": [
      {
        "title": "安全に始める",
        "body": "プラグインをインストールし、ローカルまたはクラウドの LLM プロバイダを設定して、最初のノート処理ワークフローを実行してみましょう。",
        "href": "/docs/getting-started/quick-start"
      },
      {
        "title": "プロバイダの選択",
        "body": "OpenAI 互換、Anthropic、Google、中国向け、ゲートウェイ、ローカルモデルの各オプションを比較できます。",
        "href": "/docs/providers/overview"
      },
      {
        "title": "知識ベースの構築",
        "body": "構造化されたウィキリンク、コンセプトノート、調査、翻訳、図表生成を繰り返し利用できるシステムとして活用できます。",
        "href": "/docs/pillar-ai-knowledge"
      }
    ]
  },
  "ko": {
    "title": "Notemd 문서화",
    "description": "Obsidian 노트를 위한 AI 기반의 지식 워크플로우입니다.",
    "eyebrow": "Obsidian 플러그인 문서화",
    "heading": "Notemd",
    "lead": "위키 링크, 콘셉트 노트, 연구 요약, 번역, 다이어그램 및 재사용 가능한 원클릭 워크플로우를 활용하여 노트에서 지속적인 지식을 구축하세요.",
    "primary": "문서 읽기",
    "secondary": "빠른 시작",
    "faq": "FAQ",
    "factHeading": "출처가 명시된 제품 사실 정보",
    "facts": [
      {
        "label": "워크플로우 모델",
        "value": "채팅 기록이 아닌, 먼저 작성하는 방식의 Obsidian 자동화입니다."
      },
      {
        "label": "제공업체 옵션",
        "value": "36개의 클라우드, 게이트웨이, 중국 기반, 그리고 로컬 LLM 제공업체가 있습니다."
      },
      {
        "label": "보관소 경계",
        "value": "출력 결과는 로컬 Markdown 파일에 다시 저장됩니다."
      },
      {
        "label": "현재 릴리스 버전",
        "value": "버전 1.9.7의 공개 문서 및 릴리스 자산입니다."
      }
    ],
    "retrievalHeading": "답변 엔진 소스 맵",
    "retrievalLead": "공개 사이트는 이제 llms.txt, sitemap, hreflang 메타데이터, JSON-LD가 설명하는 것과 동일한 표준 경로를 제공합니다. 이 페이지들을 AI 검색 및 인용 워크플로우의 신뢰할 수 있는 정보원으로 활용하세요.",
    "languageBoundary": "언어 경계: 영어와 번체 중국어는 인덱싱이 가능한 문서로 확인되었으며, 그 외의 모든 로케일 경로는 검토를 위해 그대로 제공되고 기계 번역된 것으로 표시됩니다.",
    "retrievalLinks": [
      {
        "title": "llms.txt 검색 맵",
        "body": "답변 엔진, 표준 문서, 제공업체 관련 항목, 그리고 현재의 다국어 경로 세트를 위한 간결한 경로 맵입니다.",
        "href": "/llms.txt",
        "kind": "static"
      },
      {
        "title": "제공업체 설정",
        "body": "운영 설정, 엔드포인트/인증 동작, 모델 검색, 문제 해결 방법, 그리고 사용 사례의 범위에 대한 내용입니다.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "AI 지식 워크플로우",
        "body": "위키 링크, 콘셉트 노트, 연구, 번역, 다이어그램 및 워크플로우에 관한 표준적인 핵심 페이지입니다.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ],
    "sections": [
      {
        "title": "안전하게 시작하기",
        "body": "플러그인을 설치하고, 로컬 또는 클라우드 기반의 LLM 제공업체를 설정한 다음, 첫 번째 노트 처리 워크플로우를 실행해 보세요.",
        "href": "/docs/getting-started/quick-start"
      },
      {
        "title": "제공업체 선택하기",
        "body": "OpenAI와 호환되는 옵션, Anthropic, Google, 중국 중심의 옵션, 게이트웨이, 그리고 로컬 모델 옵션들을 비교해 보세요.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "지식 베이스 구축하기",
        "body": "구조화된 위키 링크, 콘셉트 노트, 연구, 번역, 다이어그램 생성 기능을 반복 가능한 시스템으로 활용하여 지식 베이스를 구축하세요.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ]
  },
  "ms": {
    "title": "Dokumentasi Notemd",
    "description": "Aliran kerja pengetahuan berasaskan AI untuk nota Obsidian.",
    "eyebrow": "Dokumentasi plugin Obsidian",
    "heading": "Notemd",
    "lead": "Bina pengetahuan yang kekal daripada nota menggunakan pautan wiki, nota konsep, ringkasan penyelidikan, terjemahan, diagram, serta aliran kerja satu klik yang boleh diguna semula.",
    "primary": "Baca dokumen",
    "secondary": "Permulaan pantas",
    "faq": "FAQ",
    "factHeading": "Fakta produk yang disokong oleh sumber",
    "facts": [
      {
        "label": "Model aliran kerja",
        "value": "Automasi Obsidian jenis tulis-dahulu, bukan transkrip perbualan"
      },
      {
        "label": "Pilihan penyedia",
        "value": "36 penyedia LLM dalam bentuk awan, gateway, China, dan tempatan"
      },
      {
        "label": "Sempadan Vault",
        "value": "Keluaran akan ditulis semula ke dalam fail Markdown tempatan"
      },
      {
        "label": "Versi terkini",
        "value": "Dokumen awam versi 1.9.7 serta aset pelepasan"
      }
    ],
    "retrievalHeading": "Peta sumber enjin jawapan",
    "retrievalLead": "Laman web awam kini memaparkan laluan kanonik yang sama seperti yang diterangkan oleh llms.txt, sitemap, metadata hreflang, dan JSON-LD. Gunakan halaman-halaman ini sebagai sumber kebenaran untuk aliran kerja carian AI dan rujukan.",
    "languageBoundary": "Sempadan bahasa: Dokumen yang boleh diindeks dalam bahasa Inggeris dan Cina Ringkas telah disahkan; semua laluan bahasa lain masih tersedia untuk semakan dan ditandakan sebagai terjemahan mesin.",
    "retrievalLinks": [
      {
        "title": "Peta pemulihan llms.txt",
        "body": "Peta laluan ringkas untuk enjin jawapan, dokumen kanonik, topik penyedia, serta set laluan pelbagai bahasa terkini.",
        "href": "/llms.txt",
        "kind": "static"
      },
      {
        "title": "Konfigurasi penyedia",
        "body": "Pengaturan operasi, tingkah laku endpoint/auth, penemuan model, penyelesaian masalah, serta sempadan kes penggunaan.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "Aliran kerja pengetahuan AI",
        "body": "Halaman utama kanonik untuk pautan wiki, nota konsep, penyelidikan, terjemahan, diagram, dan aliran kerja.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ],
    "sections": [
      {
        "title": "Mulakan dengan selamat",
        "body": "Pasang plugin tersebut, konfigurasikan penyedia LLM tempatan atau awan, dan jalankan aliran kerja pemprosesan nota pertama anda.",
        "href": "/docs/getting-started/quick-start"
      },
      {
        "title": "Pilih penyedia",
        "body": "Bandingkan pilihan model yang serasi dengan OpenAI, Anthropic, Google, yang fokus pada China, gateway, serta model tempatan.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "Bina pangkalan pengetahuan",
        "body": "Gunakan pautan wiki yang terstruktur, nota konsep, penyelidikan, terjemahan, dan penghasilan diagram sebagai sistem yang boleh diulang.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ]
  },
  "nl": {
    "title": "Notemd-documentatie",
    "description": "AI-aangedreven kenniswerkflows voor Obsidian-notities.",
    "eyebrow": "Documentatie van de Obsidian-plugin",
    "heading": "Notemd",
    "lead": "Maak permanente kennis op uit notities met wiki-links, conceptnotities, onderzoeks samenvattingen, vertalingen, diagrammen en herbruikbare één-klik workflows.",
    "primary": "Lees de documentatie",
    "secondary": "Snel starten",
    "faq": "FAQ",
    "factHeading": "Productfeiten gebaseerd op bronnen",
    "facts": [
      {
        "label": "Workflowmodel",
        "value": "Obsidian-automatisering waarbij eerst wordt geschreven, geen chattranscript"
      },
      {
        "label": "Provider-overzicht",
        "value": "36 cloud-, gateway-, China- en lokale LLM-providers"
      },
      {
        "label": "Vault-grenzen",
        "value": "De uitvoer wordt opnieuw opgeslagen in lokale Markdown-bestanden"
      },
      {
        "label": "Huidige release",
        "value": "Versie 1.9.7: openbare documentatie en release-assets"
      }
    ],
    "retrievalHeading": "Bronmap van de antwoordengine",
    "retrievalLead": "De publieke site biedt nu dezelfde canonieke routes die door llms.txt, sitemap, hreflang-metadata en JSON-LD worden beschreven. Gebruik deze pagina’s als bron van waarheid voor AI-zoek- en citatie-workflows.",
    "languageBoundary": "Taalgrens: Engels en vereenvoudigd Chinees zijn geverifieerd als indexeerbare documentoppervlakken; alle andere taalroutes blijven beschikbaar voor review en zijn gemarkeerd als door een machine vertaald.",
    "retrievalLinks": [
      {
        "title": "Retrieval-map van llms.txt",
        "body": "Compacte route-map voor antwoordengines, canonieke documentatie, provider-topics en het huidige multilinguele route-set.",
        "href": "/llms.txt",
        "kind": "static"
      },
      {
        "title": "Provider-configuratie",
        "body": "Operationele opstelling, endpoint/auth-behavior, modelontdekking, foutoplossing en grenzen van gebruiksscenario’s.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "AI-kennisworkflow",
        "body": "De canonieke hoofdpagina voor wiki-links, conceptnotities, onderzoek, vertalingen, diagrammen en workflows.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ],
    "sections": [
      {
        "title": "Veilig starten",
        "body": "Installeer de plugin, configureer een lokale of cloud LLM-provider en voer je eerste notieverwerkingsworkflow uit.",
        "href": "/docs/getting-started/quick-start"
      },
      {
        "title": "Providers kiezen",
        "body": "Vergelijk OpenAI-compatibele, Anthropic-, Google-, China-gerichte, gateway- en lokale modelopties.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "Een kennisbase bouwen",
        "body": "Gebruik gestructureerde wiki-links, conceptnotities, onderzoek, vertalingen en diagramgeneratie als een herhaalbaar systeem.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ]
  },
  "no": {
    "title": "Notemd-dokumentasjon",
    "description": "AI-støttede kunnskapswerkfløyer for Obsidian-notater.",
    "eyebrow": "Obsidian-plugin-dokumentasjon",
    "heading": "Notemd",
    "lead": "Bygg permanent kunnskap fra notater med wiki-linker, konseptnotater, forskningsoppsummeringer, oversettelse, diagrammer og brukbare en-klikk-workflower.",
    "primary": "Lese dokumentasjonen",
    "secondary": "Snabb start",
    "faq": "FAQ",
    "factHeading": "Produktfakta støttet av kilder",
    "facts": [
      {
        "label": "Workflow-modell",
        "value": "Obsidian-automatisering basert på skrivning først, ikke en chat-transkripsjon"
      },
      {
        "label": "Tilbudsgrense",
        "value": "36 moln-, gateway-, Kina- og lokal LLM-tilbud"
      },
      {
        "label": "Vault-grense",
        "value": "Utdata skrives tilbake i lokale Markdown-filer"
      },
      {
        "label": "Aktuell utgave",
        "value": "Versjon 1.9.7 – offentlige dokumenter og utgivelsesressurser"
      }
    ],
    "retrievalHeading": "Kildekart for svarmaskiner",
    "retrievalLead": "Den offentlige siden eksponerer nå samme kanoniske ruter som llms.txt, sitemap, hreflang-metadata og JSON-LD beskriver. Bruk disse sidene som kilden til sannhet for AI-søk og citasjeworkflower.",
    "languageBoundary": "Språkgrænse: Engelsk og simplificeret kinesisk er verifiserte, indeksbare dokumentydelser; alle andre lokalspråksruter er fortsatt tilgjengelige for granskning og er markeret som maskintolket.",
    "retrievalLinks": [
      {
        "title": "llms.txt-retrieval-kart",
        "body": "Kompakt ruterkart for svarmaskiner, kanoniske dokumenter, tilbudstemar og den aktuelle multilinguale ruttesetten.",
        "href": "/llms.txt",
        "kind": "static"
      },
      {
        "title": "Konfigurasjon av tilbud",
        "body": "Operasjonsinnstilling, endpoint/auth-behov, modelloppdagelse, feilforskning og grenser for bruksskjermer.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "AI-kunnskapswerkfløye",
        "body": "Den kanoniske hovedsiden for wiki-linker, konseptnotater, forskning, oversettelse, diagrammer og workflower.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ],
    "sections": [
      {
        "title": "Start sikrt",
        "body": "Installert pluginet, konfigureret en lokal eller molnbasert LLM-tilbud og kjørt din første noterbehandlingsworkflow.",
        "href": "/docs/getting-started/quick-start"
      },
      {
        "title": "Välj tilbud",
        "body": "Jämför OpenAI-kompatible, Anthropic, Google, Kina-orienterte, gateway- og lokale modellalternativer.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "Bygg en kunnskapsbasé",
        "body": "Bruk strukturert wiki-linking, konseptnotater, forskning, oversettelse og diagramgenerering som et gjentatt system.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ]
  },
  "pl": {
    "title": "Dokumentacja Notemd",
    "description": "Przepływy pracy oparte na AI do notatek w Obsidian.",
    "eyebrow": "Dokumentacja wtyczki Obsidian",
    "heading": "Notemd",
    "lead": "Twórz trwałą bazę wiedzy z notatek za pomocą linków wiki, notatek koncepcyjnych, streszczeń badań, tłumaczeń, diagramów oraz powtarzalnych przepływów pracy jednym kliknięciem.",
    "primary": "Przeczytaj dokumentację",
    "secondary": "Szybki start",
    "faq": "FAQ",
    "factHeading": "Fakty o produkcie potwierdzone źródłami",
    "facts": [
      {
        "label": "Model przepływu pracy",
        "value": "Automatyzacja w Obsidian typu write-first, a nie transkrypcja rozmowy"
      },
      {
        "label": "Zasoby dostawców",
        "value": "36 dostawców LLM w chmurze, przez bramki, w Chinach oraz lokalnych"
      },
      {
        "label": "Granice Vault",
        "value": "Wyniki są zapisywane z powrotem do lokalnych plików Markdown"
      },
      {
        "label": "Obecna wersja",
        "value": "Dokumentacja publiczna wersji 1.9.7 oraz zasoby wydania"
      }
    ],
    "retrievalHeading": "Mapa źródeł silnika odpowiedzi",
    "retrievalLead": "Strona publiczna teraz udostępnia te same kanoniczne ścieżki, które opisują pliki llms.txt, sitemap, metadane hreflang oraz JSON-LD. Używaj tych stron jako źródła prawdy dla przepływów pracy związanych z wyszukiwaniem AI i cytowaniem.",
    "languageBoundary": "Granica językowa: dokumenty w języku angielskim i chińskim uproszczonym zostały zweryfikowane jako nadające się do indeksowania; wszystkie pozostałe ścieżki lokalizacyjne są nadal dostępne do przejrzenia i oznaczone jako przetłumaczone maszynowo.",
    "retrievalLinks": [
      {
        "title": "Mapa wyszukiwania llms.txt",
        "body": "Kompaktowa mapa ścieżek dla silników odpowiedzi, kanonicznych dokumentów, tematów dostawców oraz obecnego wielojęzycznego zestawu ścieżek.",
        "href": "/llms.txt",
        "kind": "static"
      },
      {
        "title": "Konfiguracja dostawców",
        "body": "Ustawienia operacyjne, zachowanie endpoint/auth, odkrywanie modeli, rozwiązywanie problemów oraz granice przypadków użycia.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "Przepływ pracy wiedzy AI",
        "body": "Kanoniczna strona filarowa dla linków wiki, notatek koncepcyjnych, badań, tłumaczeń, diagramów oraz przepływów pracy.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ],
    "sections": [
      {
        "title": "Rozpocznij bezpiecznie",
        "body": "Zainstaluj wtyczkę, skonfiguruj lokalnego lub chmurowego dostawcę LLM oraz uruchom swój pierwszy przepływ pracy przetwarzania notatek.",
        "href": "/docs/getting-started/quick-start"
      },
      {
        "title": "Wybierz dostawców",
        "body": "Porównaj opcje kompatybilne z OpenAI, Anthropic, Google, skupione na Chinach, przez bramki oraz lokalne modele.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "Stwórz bazę wiedzy",
        "body": "Wykorzystuj ustrukturyzowane linki wiki, notatki koncepcyjne, badania, tłumaczenia oraz generowanie diagramów jako powtarzalny system.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ]
  },
  "pt": {
    "title": "Documentação do Notemd",
    "description": "Fluxos de trabalho de conhecimento baseados em IA para notas do Obsidian.",
    "eyebrow": "Documentação do plugin para Obsidian",
    "heading": "Notemd",
    "lead": "Crie um conhecimento persistente a partir de notas usando links wiki, notas conceituais, resumos de pesquisa, traduções, diagramas e fluxos de trabalho reutilizáveis com um único clique.",
    "primary": "Leia a documentação",
    "secondary": "Início rápido",
    "faq": "Perguntas frequentes",
    "factHeading": "Fatos do produto com base em fontes confiáveis",
    "facts": [
      {
        "label": "Modelo de fluxo de trabalho",
        "value": "Automação no Obsidian com escrita em primeiro lugar, e não uma transcrição de conversa"
      },
      {
        "label": "Lista de provedores",
        "value": "36 provedores de LLM em nuvem, gateway, na China e locais"
      },
      {
        "label": "Limites do vault",
        "value": "Os resultados são gravados de volta em arquivos Markdown locais"
      },
      {
        "label": "Versão atual",
        "value": "Documentação pública da versão 1.9.7 e ativos de lançamento"
      }
    ],
    "retrievalHeading": "Mapa de fontes do mecanismo de resposta",
    "retrievalLead": "O site público agora exibe as mesmas rotas canônicas descritas por llms.txt, sitemap, metadados hreflang e JSON-LD. Use essas páginas como fonte de verdade para fluxos de trabalho de busca e citação por IA.",
    "languageBoundary": "Limite de idioma: os documentos indexáveis em inglês e chinês simplificado foram verificados; todas as outras rotas de localização permanecem disponíveis para revisão e estão marcadas como traduzidas por máquina.",
    "retrievalLinks": [
      {
        "title": "Mapa de recuperação do llms.txt",
        "body": "Mapa de rotas compacto para mecanismos de resposta, documentos canônicos, tópicos de provedores e o conjunto atual de rotas multilíngues.",
        "href": "/llms.txt",
        "kind": "static"
      },
      {
        "title": "Configuração de provedores",
        "body": "Configuração operacional, comportamento de endpoint/auth, descoberta de modelos, solução de problemas e limites de casos de uso.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "Fluxo de trabalho de conhecimento por IA",
        "body": "A página principal canônica para links wiki, notas conceituais, pesquisa, traduções, diagramas e fluxos de trabalho.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ],
    "sections": [
      {
        "title": "Comece com segurança",
        "body": "Instale o plugin, configure um provedor de LLM local ou em nuvem e execute seu primeiro fluxo de trabalho de processamento de notas.",
        "href": "/docs/getting-started/quick-start"
      },
      {
        "title": "Escolha os provedores",
        "body": "Compare opções compatíveis com OpenAI, Anthropic, Google, focadas na China, gateway e modelos locais.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "Crie uma base de conhecimento",
        "body": "Use links wiki estruturados, notas conceituais, pesquisa, traduções e geração de diagramas como um sistema repetível.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ]
  },
  "pt-BR": {
    "title": "Documentação do Notemd",
    "description": "Fluxos de trabalho de conhecimento baseados em IA para notas do Obsidian.",
    "eyebrow": "Documentação do plugin para Obsidian",
    "heading": "Notemd",
    "lead": "Crie um conhecimento persistente a partir de notas usando links wiki, notas conceituais, resumos de pesquisa, traduções, diagramas e fluxos de trabalho reutilizáveis com um único clique.",
    "primary": "Leia a documentação",
    "secondary": "Início rápido",
    "faq": "Perguntas frequentes",
    "factHeading": "Fatos do produto com base em fontes confiáveis",
    "facts": [
      {
        "label": "Modelo de fluxo de trabalho",
        "value": "Automação no Obsidian com escrita em primeiro lugar, e não uma transcrição de conversa"
      },
      {
        "label": "Lista de provedores",
        "value": "36 provedores de LLM em nuvem, gateway, na China e locais"
      },
      {
        "label": "Limites do vault",
        "value": "Os resultados são gravados de volta em arquivos Markdown locais"
      },
      {
        "label": "Versão atual",
        "value": "Documentação pública da versão 1.9.7 e ativos de lançamento"
      }
    ],
    "retrievalHeading": "Mapa de fontes do mecanismo de resposta",
    "retrievalLead": "O site público agora exibe as mesmas rotas canônicas descritas por llms.txt, sitemap, metadados hreflang e JSON-LD. Use essas páginas como fonte de verdade para fluxos de trabalho de busca e citação por IA.",
    "languageBoundary": "Limite de idioma: os documentos indexáveis em inglês e chinês simplificado foram verificados; todas as outras rotas de localização permanecem disponíveis para revisão e estão marcadas como traduzidas por máquina.",
    "retrievalLinks": [
      {
        "title": "Mapa de recuperação do llms.txt",
        "body": "Mapa de rotas compacto para mecanismos de resposta, documentos canônicos, tópicos de provedores e o conjunto atual de rotas multilíngues.",
        "href": "/llms.txt",
        "kind": "static"
      },
      {
        "title": "Configuração de provedores",
        "body": "Configuração operacional, comportamento de endpoint/auth, descoberta de modelos, solução de problemas e limites de casos de uso.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "Fluxo de trabalho de conhecimento por IA",
        "body": "A página principal canônica para links wiki, notas conceituais, pesquisa, traduções, diagramas e fluxos de trabalho.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ],
    "sections": [
      {
        "title": "Comece com segurança",
        "body": "Instale o plugin, configure um provedor de LLM local ou em nuvem e execute seu primeiro fluxo de trabalho de processamento de notas.",
        "href": "/docs/getting-started/quick-start"
      },
      {
        "title": "Escolha os provedores",
        "body": "Compare opções compatíveis com OpenAI, Anthropic, Google, focadas na China, gateway e modelos locais.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "Crie uma base de conhecimento",
        "body": "Use links wiki estruturados, notas conceituais, pesquisa, traduções e geração de diagramas como um sistema repetível.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ]
  },
  "ro": {
    "title": "Documentația Notemd",
    "description": "Fluxuri de lucru de cunoaștere alimentate de AI pentru notele Obsidian.",
    "eyebrow": "Documentația pluginului Obsidian",
    "heading": "Notemd",
    "lead": "Construiți o cunoaștere persistentă din note prin linkuri wiki, note conceptuale, rezumate de cercetare, traduceri, diagrame și fluxuri de lucru reutilizabile cu un singur clic.",
    "primary": "Citiți documentația",
    "secondary": "Start rapid",
    "faq": "FAQ",
    "factHeading": "Fapte despre produs bazate pe surse",
    "facts": [
      {
        "label": "Modelul de flux de lucru",
        "value": "Automatizare în Obsidian cu scriere în primul rând, nu o transcripție de chat"
      },
      {
        "label": "Listă de furnizori",
        "value": "36 de furnizori LLM în cloud, gateway, din China și locali"
      },
      {
        "label": "Granița Vault",
        "value": "Rezultatele sunt scrise înapoi în fișiere locale Markdown"
      },
      {
        "label": "Versiunea curentă",
        "value": "Documentație publică și resurse de lansare pentru versiunea 1.9.7"
      }
    ],
    "retrievalHeading": "Harta surselor motorului de răspunsuri",
    "retrievalLead": "Site-ul public expune acum aceleași route canonice descrise de llms.txt, sitemap, metadate hreflang și JSON-LD. Folosiți aceste pagini ca sursă a adevărului pentru fluxurile de lucru de căutare și citare AI.",
    "languageBoundary": "Granița de limbă: documentele indexabile în engleză și chineză simplificată au fost verificate; toate celelalte rute de limbaj rămân disponibile pentru revizuire și sunt marcate ca fiind traduse de mașină.",
    "retrievalLinks": [
      {
        "title": "Harta de recuperare llms.txt",
        "body": "O hartă compactă a route-urilor pentru motoarele de răspunsuri, documentația canonică, subiectele furnizorilor și setul curent de route multilingvă.",
        "href": "/llms.txt",
        "kind": "static"
      },
      {
        "title": "Configurarea furnizorilor",
        "body": "Setup operațional, comportamentul endpoint/auth, descoperirea modelurilor, rezolvarea problemelor și granițele cazurilor de utilizare.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "Fluxul de lucru de cunoaștere AI",
        "body": "Pagina pilon canonică pentru linkuri wiki, note conceptuale, cercetare, traduceri, diagrame și fluxuri de lucru.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ],
    "sections": [
      {
        "title": "Începeți în siguranță",
        "body": "Instalați pluginul, configurați un furnizor LLM local sau din cloud și rulați primul dumneavoastră flux de lucru de procesare a notelor.",
        "href": "/docs/getting-started/quick-start"
      },
      {
        "title": "Alegeți furnizorii",
        "body": "Comparați opțiunile compatibile cu OpenAI, Anthropic, Google, axate pe China, gateway și modele locale.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "Construiți o bază de cunoaștere",
        "body": "Folosiți linkuri wiki structurate, note conceptuale, cercetare, traduceri și generarea de diagrame ca sistem repetabil.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ]
  },
  "ru": {
    "title": "Документация Notemd",
    "description": "Рабочие процессы работы с знаниями с использованием ИИ для заметок в Obsidian.",
    "eyebrow": "Документация плагина Obsidian",
    "heading": "Notemd",
    "lead": "Создавайте постоянные базы знаний на основе заметок с помощью вики-ссылок, концептуальных заметок, кратких обзоров исследований, функций перевода, диаграмм и повторно используемых однокликовых рабочих процессов.",
    "primary": "Прочитать документацию",
    "secondary": "Быстрое начало",
    "faq": "Часто задаваемые вопросы",
    "factHeading": "Факты о продукте, подтверждённые источниками",
    "facts": [
      {
        "label": "Модель рабочего процесса",
        "value": "Автоматизация в Obsidian с первичным вводом текста, а не транскрипт чата"
      },
      {
        "label": "Набор поставщиков моделей",
        "value": "36 облачных, шлюзовых, китайских и локальных поставщиков LLM"
      },
      {
        "label": "Границы хранилища",
        "value": "Результаты обработки записываются обратно в локальные файлы формата Markdown"
      },
      {
        "label": "Текущая версия",
        "value": "Документация и ресурсы для версии 1.9.7"
      }
    ],
    "retrievalHeading": "Карта источников движка ответов",
    "retrievalLead": "Публичный сайт теперь предоставляет те же канонические маршруты, что описываются в файлах llms.txt, sitemap, метаданных hreflang и JSON-LD. Используйте эти страницы в качестве источника правды для рабочих процессов поиска с помощью ИИ и цитирования.",
    "languageBoundary": "Граница языков: документы на английском и упрощённом китайском проверены как подлежащие индексации; все остальные маршруты для других локалей остаются доступными для рассмотрения и отмечены как переведённые с помощью машинного переводчика.",
    "retrievalLinks": [
      {
        "title": "Карта поиска llms.txt",
        "body": "Компактная карта маршрутов для движков ответов, канонической документации, тем поставщиков и текущего многоязычного набора маршрутов.",
        "href": "/llms.txt",
        "kind": "static"
      },
      {
        "title": "Настройка поставщиков",
        "body": "Операционная настройка, поведение конечных точек/аутентификации, поиск моделей, устранение неполадок и границы сценариев использования.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "Рабочий процесс работы с знаниями с ИИ",
        "body": "Каноническая основная страница, посвящённая вики-ссылкам, концептуальным заметкам, исследованиям, переводу, диаграммам и рабочим процессам.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ],
    "sections": [
      {
        "title": "Начните безопасно",
        "body": "Установите плагин, настройте локального или облачного поставщика LLM и запустите свой первый рабочий процесс обработки заметок.",
        "href": "/docs/getting-started/quick-start"
      },
      {
        "title": "Выбор поставщиков",
        "body": "Сравните варианты моделей, совместимые с OpenAI, Anthropic, Google, ориентированные на Китай, шлюзовые и локальные.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "Создание базы знаний",
        "body": "Используйте структурированные вики-ссылки, концептуальные заметки, исследования, перевод и генерацию диаграмм как повторяемую систему.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ]
  },
  "sv": {
    "title": "Notemd-dokumentation",
    "description": "AI-styrda kunskapsarbetsflöden för Obsidian-noter.",
    "eyebrow": "Obsidian-plugin-dokumentation",
    "heading": "Notemd",
    "lead": "Bygg permanent kunskap från noter med wiki-länkar, konceptnoter, forskningssammanfattningar, översättning, diagram och återanvändbara en-klick-arbetsflöden.",
    "primary": "Läs dokumentationen",
    "secondary": "Snabbstart",
    "faq": "FAQ",
    "factHeading": "Produktfakta stödda av källor",
    "facts": [
      {
        "label": "Arbetsflödesmodell",
        "value": "Obsidian-automatisering med skrivning först, inte en chatttranskript"
      },
      {
        "label": "Tillhandahållarelista",
        "value": "36 moln-, gateway-, Kina- och lokala LLM-tillhandahållare"
      },
      {
        "label": "Vault-gräns",
        "value": "Utdata skrivs tillbaka i lokala Markdown-filer"
      },
      {
        "label": "Aktuell version",
        "value": "Version 1.9.7 – offentliga dokumentationer och utgivningsresurser"
      }
    ],
    "retrievalHeading": "Källkarta för svarsmaskiner",
    "retrievalLead": "Den offentliga sidan exponerar nu samma kanoniska sökvägar som llms.txt, sitemap, hreflang-metadata och JSON-LD beskriver. Använd dessa sidor som källa till sanning för AI-sökning och citeringsarbetsflöden.",
    "languageBoundary": "Språkgräns: Dokumenten på engelska och kinesiska förenklad har verifierats som indexbara; alla andra språksalternativ är fortfarande tillgängliga för granskning och har märkts som maskintöllade.",
    "retrievalLinks": [
      {
        "title": "llms.txt-sökarkarta",
        "body": "Kompakt sökvägskarta för svarsmaskiner, kanoniska dokumentationer, tillhandahållartopikar och den nuvarande flerspråkiga sökvägsuppsättningen.",
        "href": "/llms.txt",
        "kind": "static"
      },
      {
        "title": "Konfiguration av tillhandahållare",
        "body": "Operativ inställning, endpoint/auth-beteende, modellupptäckt, felsökning och gränser för användningsfall.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "AI-kunskapsarbetsflöde",
        "body": "Den kanoniska huvudsidsen för wiki-länkar, konceptnoter, forskning, översättning, diagram och arbetsflöden.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ],
    "sections": [
      {
        "title": "Starta säkert",
        "body": "Installera pluginen, konfigurera en lokal eller molnbasad LLM-tillhandahållare och kör ditt första notbearbetningsarbetsflöde.",
        "href": "/docs/getting-started/quick-start"
      },
      {
        "title": "Välj tillhandahållare",
        "body": "Jämför OpenAI-kompatibla, Anthropic-, Google-, Kina-inriktade, gateway- och lokala modellalternativ.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "Bygg en kunskapsbas",
        "body": "Använd strukturerad wiki-länkning, konceptnoter, forskning, översättning och diagramgenerering som ett återanvändbart system.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ]
  },
  "th": {
    "title": "เอกสาร Notemd",
    "description": "กระบวนการทำงานด้านความรู้ที่ขับเคลื่อนด้วย AI สำหรับบันทึกใน Obsidian。",
    "eyebrow": "เอกสารปลั๊กอิน Obsidian",
    "heading": "Notemd",
    "lead": "สร้างความรู้ที่คงอยู่ตลอดไปจากบันทึกต่าง ๆ ด้วยลิงก์ wiki, บันทึกแนวคิด, สรุปผลการวิจัย, การแปล, แผนภาพ, และกระบวนการทำงานแบบคลิกเดียวที่สามารถนำกลับมาใช้ซ้ำได้。",
    "primary": "อ่านเอกสาร",
    "secondary": "เริ่มต้นใช้งานอย่างรวดเร็ว",
    "faq": "คำถามที่พบบ่อย",
    "factHeading": "ข้อเท็จจริงเกี่ยวกับผลิตภัณฑ์ที่มีแหล่งที่มายืนยัน",
    "facts": [
      {
        "label": "รูปแบบกระบวนการทำงาน",
        "value": "เป็นการอัตโนมัติใน Obsidian ที่เน้นการเขียนก่อน ไม่ใช่บันทึกการสนทนา"
      },
      {
        "label": "รายชื่อผู้ให้บริการ",
        "value": "มีผู้ให้บริการ LLM บนคลาวด์ 36 ราย, ผู้ให้บริการแบบเกตเวย์, ผู้ให้บริการในประเทศจีน, และผู้ให้บริการแบบท้องถิ่น"
      },
      {
        "label": "ขอบเขตของ Vault",
        "value": "ผลลัพธ์จะถูกเขียนกลับเข้าไปในไฟล์ Markdown ที่อยู่ในเครื่อง"
      },
      {
        "label": "เวอร์ชันปัจจุบัน",
        "value": "มีเอกสารสาธารณะและไฟล์ทรัพยากรสำหรับเวอร์ชัน 1.9.7"
      }
    ],
    "retrievalHeading": "แผนที่แหล่งข้อมูลของเครื่องมือตอบคำถาม",
    "retrievalLead": "เว็บไซต์สาธารณะปัจจุบันเปิดเผยเส้นทางมาตรฐานเดียวกันกับที่ llms.txt, sitemap, ข้อมูล metadata hreflang และ JSON-LD ระบุไว้ ให้ใช้หน้าเหล่านี้เป็นแหล่งข้อมูลที่ถูกต้องสำหรับกระบวนการค้นหาด้วย AI และการอ้างอิง。",
    "languageBoundary": "ขอบเขตภาษา: เอกสารที่สามารถจัดทำดัชนีได้ได้รับการยืนยันว่าเป็นภาษาอังกฤษและภาษาจีนตัวย่อ; เส้นทางภาษาอื่น ๆ ทั้งหมดยังคงสามารถใช้งานเพื่อการตรวจสอบได้ และถูกทำเครื่องหมายว่าเป็นเอกสารที่แปลโดยเครื่อง",
    "retrievalLinks": [
      {
        "title": "แผนที่การค้นหา llms.txt",
        "body": "แผนที่เส้นทางแบบกระชับสำหรับเครื่องมือตอบคำถาม, เอกสารมาตรฐาน, หัวข้อของผู้ให้บริการ, และชุดเส้นทางหลายภาษาปัจจุบัน",
        "href": "/llms.txt",
        "kind": "static"
      },
      {
        "title": "การกำหนดค่าผู้ให้บริการ",
        "body": "การตั้งค่าการใช้งาน, พฤติกรรม endpoint/auth, การค้นหาโมเดล, การแก้ไขปัญหา, และขอบเขตของกรณีการใช้งาน",
        "href": "/docs/providers/overview"
      },
      {
        "title": "กระบวนการทำงานด้านความรู้ด้วย AI",
        "body": "หน้าหลักมาตรฐานสำหรับลิงก์ wiki, บันทึกแนวคิด, การวิจัย, การแปล, แผนภาพ, และกระบวนการทำงานต่าง ๆ",
        "href": "/docs/pillar-ai-knowledge"
      }
    ],
    "sections": [
      {
        "title": "เริ่มต้นอย่างปลอดภัย",
        "body": "ติดตั้งปลั๊กอิน, กำหนดค่าผู้ให้บริการ LLM แบบท้องถิ่นหรือบนคลาวด์, และเรียกใช้กระบวนการประมวลผลบันทึกครั้งแรกของคุณ",
        "href": "/docs/getting-started/quick-start"
      },
      {
        "title": "เลือกผู้ให้บริการ",
        "body": "เปรียบเทียบตัวเลือกโมเดลที่รองรับ OpenAI, Anthropic, Google, โมเดลที่เน้นประเทศจีน, ผู้ให้บริการแบบเกตเวย์, และโมเดลแบบท้องถิ่น",
        "href": "/docs/providers/overview"
      },
      {
        "title": "สร้างฐานความรู้",
        "body": "ใช้การเชื่อมโยง wiki แบบมีโครงสร้าง, บันทึกแนวคิด, การวิจัย, การแปล, และการสร้างแผนภาพเป็นระบบที่สามารถทำซ้ำได้",
        "href": "/docs/pillar-ai-knowledge"
      }
    ]
  },
  "tr": {
    "title": "Notemd Dokümantasyonu",
    "description": "Obsidian notları için yapay zeka destekli bilgi iş akışları.",
    "eyebrow": "Obsidian eklentisi dokümantasyonu",
    "heading": "Notemd",
    "lead": "Wiki bağlantıları, kavram notları, araştırma özetleri, çeviri, diyagramlar ve tek tıkla kullanılabilen iş akışları ile notlardan kalıcı bir bilgi tabanı oluşturun.",
    "primary": "Dokümantasyonu oku",
    "secondary": "Hızlı başlangıç",
    "faq": "Sıkça Sorulan Sorular",
    "factHeading": "Kaynaklara dayalı ürün bilgileri",
    "facts": [
      {
        "label": "İş akışı modeli",
        "value": "Önce yazma prensibine dayalı Obsidian otomasyonu, sohbet kaydı değil"
      },
      {
        "label": "Sağlayıcı yelpazesi",
        "value": "36 bulut, ağ geçidi, Çin merkezli ve yerel LLM sağlayıcıları"
      },
      {
        "label": "Vault sınırı",
        "value": "Çıktılar yerel Markdown dosyalarına geri yazılır"
      },
      {
        "label": "Mevcut sürüm",
        "value": "Sürüm 1.9.7 için genel dokümantasyon ve sürüm dosyaları"
      }
    ],
    "retrievalHeading": "Cevap motoru kaynak haritası",
    "retrievalLead": "Kamuya açık site artık llms.txt, sitemap, hreflang meta verileri ve JSON-LD tarafından tanımlanan aynı standart yolları sunmaktadır. Bu sayfaları yapay zeka arama ve atıf iş akışları için tek doğru kaynak olarak kullanın.",
    "languageBoundary": "Dil sınırı: İngilizce ve Basitleştirilmiş Çince, indekslenebilir belge yüzeyleri olarak doğrulanmıştır; diğer tüm dil rotaları inceleme için hâlâ mevcuttur ve makine çevirisi olarak işaretlenmiştir.",
    "retrievalLinks": [
      {
        "title": "llms.txt erişim haritası",
        "body": "Cevap motorları, standart dokümanlar, sağlayıcı konuları ve mevcut çok dilli yol seti için kompakt bir yol haritası.",
        "href": "/llms.txt",
        "kind": "static"
      },
      {
        "title": "Sağlayıcı yapılandırması",
        "body": "İşletim kurulumu, uç nokta/oturum açma davranışları, model keşfi, sorun giderme ve kullanım senaryolarının sınırları.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "Yapay zeka bilgi iş akışı",
        "body": "Wiki bağlantıları, kavram notları, araştırma, çeviri, diyagramlar ve iş akışları için standart ana sayfa.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ],
    "sections": [
      {
        "title": "Güvenli bir şekilde başlayın",
        "body": "Eklentiyi yükleyin, yerel veya bulut tabanlı bir LLM sağlayıcısı yapılandırın ve ilk not işleme iş akışınızı çalıştırın.",
        "href": "/docs/getting-started/quick-start"
      },
      {
        "title": "Sağlayıcıları seçin",
        "body": "OpenAI ile uyumlu, Anthropic, Google, Çin odaklı, ağ geçidi ve yerel model seçeneklerini karşılaştırın.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "Bir bilgi tabanı oluşturun",
        "body": "Yapılandırılmış wiki bağlantıları, kavram notları, araştırma, çeviri ve diyagram oluşturma işlemlerini tekrarlanabilir bir sistem olarak kullanın.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ]
  },
  "uk": {
    "title": "Документація Notemd",
    "description": "Робочі процеси зі знаннями, що працюють за допомогою ШІ, для нотаток Obsidian.",
    "eyebrow": "Документація плагіна Obsidian",
    "heading": "Notemd",
    "lead": "Створюйте постійні знання з нотаток за допомогою веб‑посилань, концептуальних нотаток, узагальнень досліджень, перекладу, діаграм та повторно використовуваних одноклікових робочих процесів.",
    "primary": "Прочитати документацію",
    "secondary": "Швидкий старт",
    "faq": "Часто задавані запитання",
    "factHeading": "Факти про продукт, підтверджені джерелами",
    "facts": [
      {
        "label": "Модель робочого процесу",
        "value": "Автоматизація в Obsidian з написанням спочатку, а не транскрипція чату"
      },
      {
        "label": "Набір постачальників",
        "value": "36 хмарних, гейтвей‑тих, китайських та локальних постачальників LLM"
      },
      {
        "label": "Межі Vault",
        "value": "Результати записуються назад у локальні файли Markdown"
      },
      {
        "label": "Текуща версія",
        "value": "Документація та ресурси версії 1.9.7"
      }
    ],
    "retrievalHeading": "Карта джерел двигуна відповідей",
    "retrievalLead": "Публічний сайт тепер відображає ті самі канонічні маршрути, які описуються файлами llms.txt, sitemap, метаданими hreflang та JSON‑LD. Використовуйте ці сторінки як джерело істини для робочих процесів пошуку та цитування за допомогою ШІ.",
    "languageBoundary": "Межа мов: документи англійською та спрощеною китайською перевірені як придатні для індексації; усі інші маршрути локалей залишаються доступними для перегляду та позначені як автоматично перекладені.",
    "retrievalLinks": [
      {
        "title": "Карта пошуку llms.txt",
        "body": "Компактна карта маршрутів для двигунів відповідей, канонічної документації, тем постачальників та поточного багатомовного набору маршрутів.",
        "href": "/llms.txt",
        "kind": "static"
      },
      {
        "title": "Конфігурація постачальників",
        "body": "Операційна налаштування, поведінка кінцевих точок/автентифікації, виявлення моделей, усунення проблем та межі сценаріїв використання.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "Робочий процес знань ШІ",
        "body": "Канонічна основна сторінка для веб‑посилань, концептуальних нотаток, досліджень, перекладу, діаграм та робочих процесів.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ],
    "sections": [
      {
        "title": "Почніть безпечно",
        "body": "Встановіть плагін, налаштуйте локального або хмарного постачальника LLM та запустіть свій перший робочий процес обробки нотаток.",
        "href": "/docs/getting-started/quick-start"
      },
      {
        "title": "Виберіть постачальників",
        "body": "Порівняйте варіанти моделей, сумісні з OpenAI, Anthropic, Google, орієнтовані на Китай, гейтвей‑ти та локальні.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "Створіть базу знань",
        "body": "Використовуйте структуровані веб‑посилання, концептуальні нотатки, дослідження, переклад та генерацію діаграм як повторювану систему.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ]
  },
  "vi": {
    "title": "Tài liệu Notemd",
    "description": "Các quy trình làm việc dựa trên trí tuệ nhân tạo cho ghi chú trong Obsidian.",
    "eyebrow": "Tài liệu plugin Obsidian",
    "heading": "Notemd",
    "lead": "Xây dựng kho kiến thức bền vững từ các ghi chú thông qua liên kết wiki, ghi chú khái niệm, tóm tắt nghiên cứu, dịch thuật, sơ đồ, và các quy trình một cú nhấp có thể tái sử dụng.",
    "primary": "Đọc tài liệu",
    "secondary": "Bắt đầu nhanh",
    "faq": "Câu hỏi thường gặp",
    "factHeading": "Thông tin sản phẩm có cơ sở từ nguồn thực tế",
    "facts": [
      {
        "label": "Mô hình quy trình làm việc",
        "value": "Tự động hóa trong Obsidian theo kiểu viết trước, chứ không phải bản ghi cuộc trò chuyện"
      },
      {
        "label": "Các nhà cung cấp dịch vụ",
        "value": "36 nhà cung cấp LLM trên nền tảng đám mây, gateway, tại Trung Quốc, và phiên bản địa phương"
      },
      {
        "label": "Giới hạn của Vault",
        "value": "Kết quả xử lý sẽ được ghi lại vào các tệp Markdown địa phương"
      },
      {
        "label": "Phiên bản hiện tại",
        "value": "Tài liệu công khai và tài nguyên phiên bản 1.9.7"
      }
    ],
    "retrievalHeading": "Bản đồ nguồn của công cụ trả lời câu hỏi",
    "retrievalLead": "Trang web công khai hiện đã cung cấp các đường dẫn chuẩn tương tự như những gì được mô tả bởi llms.txt, sitemap, metadata hreflang, và JSON-LD. Hãy sử dụng các trang này làm nguồn thông tin chính xác cho các quy trình tìm kiếm và trích dẫn bằng trí tuệ nhân tạo.",
    "languageBoundary": "Giới hạn ngôn ngữ: Các tài liệu có thể được lập chỉ mục bằng tiếng Anh và tiếng Trung giản thể đã được xác minh; tất cả các đường dẫn ngôn ngữ khác vẫn còn sẵn để xem xét và được đánh dấu là đã được dịch tự động.",
    "retrievalLinks": [
      {
        "title": "Bản đồ truy vấn llms.txt",
        "body": "Bản đồ đường dẫn gọn gàng cho các công cụ trả lời câu hỏi, tài liệu chuẩn, các chủ đề nhà cung cấp, và bộ đường dẫn đa ngôn ngữ hiện tại.",
        "href": "/llms.txt",
        "kind": "static"
      },
      {
        "title": "Cấu hình nhà cung cấp dịch vụ",
        "body": "Thiết lập vận hành, hành vi endpoint/auth, khám phá mô hình, khắc phục sự cố, và các giới hạn trường hợp sử dụng.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "Quy trình làm việc kiến thức AI",
        "body": "Trang cột mốc chuẩn cho liên kết wiki, ghi chú khái niệm, nghiên cứu, dịch thuật, sơ đồ, và các quy trình làm việc.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ],
    "sections": [
      {
        "title": "Bắt đầu một cách an toàn",
        "body": "Cài đặt plugin, cấu hình một nhà cung cấp LLM địa phương hoặc trên đám mây, và chạy quy trình xử lý ghi chú đầu tiên của bạn.",
        "href": "/docs/getting-started/quick-start"
      },
      {
        "title": "Chọn nhà cung cấp dịch vụ",
        "body": "So sánh các tùy chọn mô hình tương thích với OpenAI, Anthropic, Google, tập trung vào Trung Quốc, gateway, và phiên bản địa phương.",
        "href": "/docs/providers/overview"
      },
      {
        "title": "Xây dựng cơ sở kiến thức",
        "body": "Sử dụng liên kết wiki có cấu trúc, ghi chú khái niệm, nghiên cứu, dịch thuật, và tạo sơ đồ như một hệ thống có thể lặp lại.",
        "href": "/docs/pillar-ai-knowledge"
      }
    ]
  },
  "zh-Hant": {
    "title": "Notemd 文件說明",
    "description": "專為 Obsidian 紙張打造的 AI 驅動型知識工作流程。",
    "eyebrow": "Obsidian 外掛文件說明",
    "heading": "Notemd",
    "lead": "透過維基連結、概念筆記、研究摘要、翻譯、圖表以及可重複使用的單鍵工作流程，從紙張中建立持久的知識體系。",
    "primary": "閱讀文件說明",
    "secondary": "快速入門",
    "faq": "常見問題",
    "factHeading": "有來源支撐的產品資訊",
    "facts": [
      {
        "label": "工作流程模型",
        "value": "採用先撰寫後自動化的 Obsidian 自動化機制，而非聊天記錄格式"
      },
      {
        "label": "供應商選項",
        "value": "涵蓋 36 種雲端、閘道型、中國區以及本地的 LLM 供應商"
      },
      {
        "label": "資料儲存範圍",
        "value": "輸出結果會被寫回本地的 Markdown 檔案中"
      },
      {
        "label": "目前版本",
        "value": "版本 1.9.7 的公開文件說明與發行檔案"
      }
    ],
    "retrievalHeading": "答案引擎的來源地圖",
    "retrievalLead": "公開網站現已提供與 llms.txt、sitemap、hreflang 中繼資料以及 JSON-LD 所描述的相同標準路徑。請將這些頁面作為 AI 搜尋與引用工作流程的權威來源。",
    "languageBoundary": "語言邊界：已確認英文及簡體中文的文件屬於可建立索引的內容；所有其他語言版本的頁面仍可供審核，且標記為機器翻譯產出。",
    "retrievalLinks": [
      {
        "title": "llms.txt 取得地圖",
        "body": "針對答案引擎、標準文件說明、供應商主題以及目前的多語言路徑集所製作的精簡路徑地圖。",
        "href": "/llms.txt",
        "kind": "static"
      },
      {
        "title": "供應商設定",
        "body": "包含運作設定、端點/認證行為、模型探索、故障排除以及使用情境的範圍說明。",
        "href": "/docs/providers/overview"
      },
      {
        "title": "AI 知識工作流程",
        "body": "涵蓋維基連結、概念筆記、研究、翻譯、圖表以及各種工作流程的標準主頁。",
        "href": "/docs/pillar-ai-knowledge"
      }
    ],
    "sections": [
      {
        "title": "安全地開始使用",
        "body": "安裝此外掛，設定本機或雲端的 LLM 供應商，然後執行您的第一個紙張處理工作流程。",
        "href": "/docs/getting-started/quick-start"
      },
      {
        "title": "選擇供應商",
        "body": "比較支援 OpenAI 的、Anthropic、Google、針對中國市場的、閘道型以及本機模型等各種選項。",
        "href": "/docs/providers/overview"
      },
      {
        "title": "建立知識庫",
        "body": "運用結構化的維基連結、概念筆記、研究、翻譯以及圖表生成功能，打造可重複使用的系統。",
        "href": "/docs/pillar-ai-knowledge"
      }
    ]
  },
  "zh-TW": {
    "title": "Notemd 文件說明",
    "description": "為 Obsidian 紙張打造的 AI 驅動型知識工作流程。",
    "eyebrow": "Obsidian 外掛文件說明",
    "heading": "Notemd",
    "lead": "透過維基連結、概念筆記、研究摘要、翻譯、圖表以及可重複使用的單鍵工作流程，從紙張中建立持久的知識體系。",
    "primary": "閱讀文件說明",
    "secondary": "快速入門",
    "faq": "常見問題",
    "factHeading": "有來源支撐的產品資訊",
    "facts": [
      {
        "label": "工作流程模型",
        "value": "採先寫後自動化的 Obsidian 自動化機制，而非聊天記錄格式"
      },
      {
        "label": "供應商選項",
        "value": "36 種雲端、閘道型、中國區以及本地的 LLM 供應商"
      },
      {
        "label": "資料儲存範圍",
        "value": "輸出結果會被寫回本地的 Markdown 檔案中"
      },
      {
        "label": "目前版本",
        "value": "版本 1.9.7 的公開文件說明與發行檔案"
      }
    ],
    "retrievalHeading": "答案引擎的來源地圖",
    "retrievalLead": "公開網站現已提供與 llms.txt、sitemap、hreflang 中繼資料以及 JSON-LD 所描述的相同標準路徑。請將這些頁面作為 AI 搜尋與引用工作流程的權威來源。",
    "languageBoundary": "語言邊界：已確認英文及簡體中文的文件屬於可建立索引的內容；所有其他語言版本的頁面仍可供審核，且標示為機器翻譯產出。",
    "retrievalLinks": [
      {
        "title": "llms.txt 搜尋地圖",
        "body": "針對答案引擎、標準文件說明、供應商主題以及目前的多語言路徑集所製作的精簡路徑地圖。",
        "href": "/llms.txt",
        "kind": "static"
      },
      {
        "title": "供應商設定",
        "body": "包含運作設定、端點/認證行為、模型探索、故障排除以及使用情境的範圍說明。",
        "href": "/docs/providers/overview"
      },
      {
        "title": "AI 知識工作流程",
        "body": "涵蓋維基連結、概念筆記、研究、翻譯、圖表以及各種工作流程的標準主頁。",
        "href": "/docs/pillar-ai-knowledge"
      }
    ],
    "sections": [
      {
        "title": "安全地開始使用",
        "body": "安裝此外掛，設定本機或雲端的 LLM 供應商，然後執行您的第一個紙張處理工作流程。",
        "href": "/docs/getting-started/quick-start"
      },
      {
        "title": "選擇供應商",
        "body": "比較支援 OpenAI 的、Anthropic、Google、針對中國市場的、閘道型以及本機模型等各種選項。",
        "href": "/docs/providers/overview"
      },
      {
        "title": "建立知識庫",
        "body": "運用結構化的維基連結、概念筆記、研究、翻譯以及圖表生成功能，打造可重複使用的系統。",
        "href": "/docs/pillar-ai-knowledge"
      }
    ]
  }
};
