export const publishedZhCnDocs = [
  {id: 'intro', path: '/docs/intro', sourcePath: 'intro.mdx'},
  {id: 'getting-started/installation', path: '/docs/getting-started/installation', sourcePath: 'getting-started/installation.mdx'},
  {id: 'getting-started/quick-start', path: '/docs/getting-started/quick-start', sourcePath: 'getting-started/quick-start.mdx'},
  {id: 'getting-started/configuration', path: '/docs/getting-started/configuration', sourcePath: 'getting-started/configuration.mdx'},
  {id: 'features/wiki-links', path: '/docs/features/wiki-links', sourcePath: 'features/wiki-links.mdx'},
  {id: 'features/concept-notes', path: '/docs/features/concept-notes', sourcePath: 'features/concept-notes.mdx'},
  {id: 'features/research', path: '/docs/features/research', sourcePath: 'features/research.mdx'},
  {id: 'features/translation', path: '/docs/features/translation', sourcePath: 'features/translation.mdx'},
  {id: 'features/diagrams', path: '/docs/features/diagrams', sourcePath: 'features/diagrams.mdx'},
  {id: 'features/workflows', path: '/docs/features/workflows', sourcePath: 'features/workflows.mdx'},
  {id: 'providers/overview', path: '/docs/providers/overview', sourcePath: 'providers/overview.mdx'},
  {id: 'providers/openai', path: '/docs/providers/openai', sourcePath: 'providers/openai.mdx'},
  {id: 'providers/anthropic', path: '/docs/providers/anthropic', sourcePath: 'providers/anthropic.mdx'},
  {id: 'providers/google', path: '/docs/providers/google', sourcePath: 'providers/google.mdx'},
  {id: 'providers/local', path: '/docs/providers/local', sourcePath: 'providers/local.mdx'},
  {id: 'providers/china', path: '/docs/providers/china', sourcePath: 'providers/china.mdx'},
  {id: 'advanced/custom-prompts', path: '/docs/advanced/custom-prompts', sourcePath: 'advanced/custom-prompts.mdx'},
  {id: 'advanced/batch-processing', path: '/docs/advanced/batch-processing', sourcePath: 'advanced/batch-processing.mdx'},
  {id: 'advanced/troubleshooting', path: '/docs/advanced/troubleshooting', sourcePath: 'advanced/troubleshooting.mdx'},
  {id: 'pillar-ai-knowledge', path: '/docs/pillar-ai-knowledge', sourcePath: 'pillar-ai-knowledge.mdx'},
  {id: 'faq', path: '/docs/faq', sourcePath: 'faq.mdx'},
  {id: 'developers/overview', path: '/docs/developers/overview', sourcePath: 'developers/overview.mdx'},
  {id: 'agents/overview', path: '/docs/agents/overview', sourcePath: 'agents/overview.mdx'},
  {id: 'releases/1.9.11', path: '/docs/releases/1.9.11', sourcePath: 'releases/1.9.11.mdx'},
  {id: 'releases/1.9.10', path: '/docs/releases/1.9.10', sourcePath: 'releases/1.9.10.mdx'},
  {id: 'releases/1.9.9', path: '/docs/releases/1.9.9', sourcePath: 'releases/1.9.9.mdx'},
  {id: 'releases/1.9.8', path: '/docs/releases/1.9.8', sourcePath: 'releases/1.9.8.mdx'},
];

export const zhCnCriticalDocPaths = publishedZhCnDocs.map((doc) => doc.path);

export const zhCnHomepageDocPaths = [
  '/docs/intro',
  '/docs/getting-started/quick-start',
  '/docs/features/workflows',
  '/docs/developers/overview',
  '/docs/agents/overview',
  '/docs/providers/overview',
  '/docs/advanced/troubleshooting',
  '/docs/faq',
];
